[project]
name = "toolbox"
version = "1.0.0"
authors = [
  { name="Paul Wilk", email="wilkp@vmware.com" },
  { name="Chris Stacks", email="stacksc@vmware.com" }
]
description = "toolbox - a library of standalone python modules ready for use"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "argparse",
  "pync",
  "gnupg",
  "cryptography",
  "gnureadline",
]

[build-system]
requires = [ "setuptools >= 42.0.0" ]
build-backend = 'setuptools.build_meta'

[tool.setuptools.packages]
find = {}

# include our emoji.lst and other data
[tool.setuptools.package-data]
"*" = ["*.lst"]

