[project]
name = "vmctools"
version = "0.0.2"
authors = [
  { name="Paul Wilk", email="wilkp@vmware.com" },
]
description = "VMCtools - CLI client for VMC"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "click"
]

[build-system]
requires = [
  "setuptools >= 40.9.0",
  "toolbox",
  "configstore"
]

[project.scripts]
vmctools = "vmctools.vmctools:cli"

[tool.setuptools.packages]
find = {}

