.TH "GOAT JIRA ISSUE ASSIGN" "1" "2023-08-06" "1.0.0" "goat jira issue assign Manual"
.SH NAME
goat\-jira\-issue\-assign \- change assignee of a given JIRA issue(s)
.SH SYNOPSIS
.B goat jira issue assign
[OPTIONS] ISSUE_KEYS...
.SH DESCRIPTION
change assignee of a given JIRA issue(s)
.SH OPTIONS
.TP
\fB\-a,\fP \-\-assignee TEXT
assignee name, i.e. stacksc
