.TH "GOAT CONFIGS ADD PROPERTY" "1" "2023-08-06" "1.0.0" "goat configs add property Manual"
.SH NAME
goat\-configs\-add\-property \- add a record to a profile stored in a...
.SH SYNOPSIS
.B goat configs add property
[OPTIONS] CONFIGSTORE_NAME... PROFILE_NAME RECORD_NAME RECORD_VALUE
.SH DESCRIPTION
add a record to a profile stored in a configstore
