.TH "GOAT AWS EC2 SHOW" "1" "2023-08-06" "1.0.0" "goat aws ec2 show Manual"
.SH NAME
goat\-aws\-ec2\-show \- show the data stored in ec2 cache...
.SH SYNOPSIS
.B goat aws ec2 show
[OPTIONS] [[all|instances|public_ips|regions|orphaned_ebs|orphaned_snaps]]
.SH DESCRIPTION
show the data stored in ec2 cache (instacnes, IPs, regions)
