.TH "GOAT JIRA ISSUE ATTACH" "1" "2023-08-06" "1.0.0" "goat jira issue attach Manual"
.SH NAME
goat\-jira\-issue\-attach \- attach a file to a given JIRA issue(s)
.SH SYNOPSIS
.B goat jira issue attach
[OPTIONS] ISSUE_KEYS...
.SH DESCRIPTION
attach a file to a given JIRA issue(s)
.SH OPTIONS
.TP
\fB\-a,\fP \-\-attach PATH
name of file to attach
