.TH "GOAT JIRA ISSUE" "1" "2023-08-06" "1.0.0" "goat jira issue Manual"
.SH NAME
goat\-jira\-issue \- manage JIRA issues
.SH SYNOPSIS
.B goat jira issue
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage JIRA issues
.SH COMMANDS
.PP
\fBsearch\fP
  show a summary of specified issue or issues
  See \fBgoat jira issue-search(1)\fP for full documentation on the \fBsearch\fP command.
.PP
\fBattach\fP
  attach a file to a given JIRA issue(s)
  See \fBgoat jira issue-attach(1)\fP for full documentation on the \fBattach\fP command.
.PP
\fBreview\fP
  change the VMC Ops Review to Yes or No for...
  See \fBgoat jira issue-review(1)\fP for full documentation on the \fBreview\fP command.
.PP
\fBassign\fP
  change assignee of a given JIRA issue(s)
  See \fBgoat jira issue-assign(1)\fP for full documentation on the \fBassign\fP command.
.PP
\fBcomment\fP
  post a comment to a given JIRA issue(s)
  See \fBgoat jira issue-comment(1)\fP for full documentation on the \fBcomment\fP command.
.PP
\fBupdate\fP
  update a field in a given JIRA issue
  See \fBgoat jira issue-update(1)\fP for full documentation on the \fBupdate\fP command.
.PP
\fBcreate\fP
  creates a new JIRA issue in a given project
  See \fBgoat jira issue-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBcomments\fP
  look for specific data in the comments of...
  See \fBgoat jira issue-comments(1)\fP for full documentation on the \fBcomments\fP command.
.PP
\fBextract\fP
  look for specific data in the description...
  See \fBgoat jira issue-extract(1)\fP for full documentation on the \fBextract\fP command.
.PP
\fBchange-plan\fP
  dump entire change implementation plan of...
  See \fBgoat jira issue-change-plan(1)\fP for full documentation on the \fBchange-plan\fP command.
.PP
\fBtransition\fP
  transition a given issue
  See \fBgoat jira issue-transition(1)\fP for full documentation on the \fBtransition\fP command.
