.TH "GOAT AWS IAM" "1" "2023-08-06" "1.0.0" "goat aws iam Manual"
.SH NAME
goat\-aws\-iam \- manage and switch between AWS profiles in...
.SH SYNOPSIS
.B goat aws iam
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage and switch between AWS profiles in GC and SIM regions
.SH COMMANDS
.PP
\fBauthenticate\fP
  login using existing IAM creds or add new...
  See \fBgoat aws iam-authenticate(1)\fP for full documentation on the \fBauthenticate\fP command.
.PP
\fBassume-role\fP
  login using existing IAM creds or add new...
  See \fBgoat aws iam-assume-role(1)\fP for full documentation on the \fBassume-role\fP command.
