.TH "GOAT AWS IAM AUTHENTICATE" "1" "2023-08-06" "1.0.0" "goat aws iam authenticate Manual"
.SH NAME
goat\-aws\-iam\-authenticate \- login using existing IAM creds or add new...
.SH SYNOPSIS
.B goat aws iam authenticate
[OPTIONS]
.SH DESCRIPTION
login using existing IAM creds or add new creds to config
.SH OPTIONS
.TP
\fB\-r,\fP \-\-region TEXT
aws region to connect to
.TP
\fB\-o,\fP \-\-output TEXT
output type for awscli
