.TH "GOAT JIRA ISSUE UPDATE" "1" "2023-08-06" "1.0.0" "goat jira issue update Manual"
.SH NAME
goat\-jira\-issue\-update \- update a field in a given JIRA issue
.SH SYNOPSIS
.B goat jira issue update
[OPTIONS] ISSUE_KEY
.SH DESCRIPTION
update a field in a given JIRA issue
.SH OPTIONS
.TP
\fB\-f,\fP \-\-field TEXT
name of the field to update i.e. reporter  [required]
.TP
\fB\-v,\fP \-\-value TEXT
new value for the field i.e. jsmith  [required]
