.TH "GOAT OCI COMPUTE REFRESH" "1" "2023-09-21" "2023.9.20.2226" "goat oci compute refresh Manual"
.SH NAME
goat\-oci\-compute\-refresh \- manually refresh compute cached data
.SH SYNOPSIS
.B goat oci compute refresh
[OPTIONS] [[all|instances|public_ips|regions|auto]]
.SH DESCRIPTION
manually refresh compute cached data
