.TH "GOAT OCI COMPUTE" "1" "2023-09-21" "2023.9.20.2226" "goat oci compute Manual"
.SH NAME
goat\-oci\-compute \- compute to manage the instances and...
.SH SYNOPSIS
.B goat oci compute
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
compute to manage the instances and related configuration
.SH OPTIONS
.TP
\fB\-m,\fP \-\-menu
use the menu to perform compute actions  [default: False]
.SH COMMANDS
.PP
\fBrefresh\fP
  manually refresh compute cached data
  See \fBgoat oci compute-refresh(1)\fP for full documentation on the \fBrefresh\fP command.
.PP
\fBshow\fP
  show the data stored in compute cache...
  See \fBgoat oci compute-show(1)\fP for full documentation on the \fBshow\fP command.
