.TH "GOAT JIRA CONFIG" "1" "2023-08-06" "1.0.0" "goat jira config Manual"
.SH NAME
goat\-jira\-config \- manage configuration details for the Jira...
.SH SYNOPSIS
.B goat jira config
[OPTIONS]
.SH DESCRIPTION
manage configuration details for the Jira server on this profile
.SH OPTIONS
.TP
\fB\-d,\fP \-\-default
mark this profile as the default profile to use for JIRA
.TP
\fB\-s,\fP \-\-show
show the entire config for the JIRA server on this profile
