.TH "GOAT OCI OSS DOWNLOAD" "1" "2024-01-24" "2024.1.19.237" "goat oci oss download Manual"
.SH NAME
goat\-oci\-oss\-download \- download from OSS to local storage
.SH SYNOPSIS
.B goat oci oss download
[OPTIONS] [SOURCE]
.SH DESCRIPTION
download from OSS to local storage
.SH OPTIONS
.TP
\fB\-\-destination\fP TEXT
provide a local destination for download  [default: /Users/stacksc]
