.TH "GOAT SLACK CHANNEL DELUSER" "1" "2023-09-21" "2023.9.20.2226" "goat slack channel deluser Manual"
.SH NAME
goat\-slack\-channel\-deluser \- delete (kick) a user from the channel
.SH SYNOPSIS
.B goat slack channel deluser
[OPTIONS]
.SH DESCRIPTION
delete (kick) a user from the channel
.SH OPTIONS
.TP
\fB\-i,\fP \-\-id TEXT
target channel
.TP
\fB\-u,\fP \-\-user TEXT
user id to kick from the channel
