.TH "GOAT ORACLE COMPUTE REFRESH" "1" "2024-02-04" "2024.2.4.728" "goat oracle compute refresh Manual"
.SH NAME
goat\-oracle\-compute\-refresh \- manually refresh compute cached data
.SH SYNOPSIS
.B goat oracle compute refresh
[OPTIONS] [[all|instances|public_ips|regions|auto]]
.SH DESCRIPTION
manually refresh compute cached data
