.TH "GOAT ORACLE VAULT SECRETS" "1" "2024-02-04" "2024.2.4.728" "goat oracle vault secrets Manual"
.SH NAME
goat\-oracle\-vault\-secrets \- module to manage secrets
.SH SYNOPSIS
.B goat oracle vault secrets
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
module to manage secrets
.SH OPTIONS
.TP
\fB\-m,\fP \-\-menu
use the menu to perform secret actions  [default: False]
.SH COMMANDS
.PP
\fBrefresh\fP
  manually refresh secrets stored in cache
  See \fBgoat oracle vault secrets-refresh(1)\fP for full documentation on the \fBrefresh\fP command.
.PP
\fBcreate\fP
  create OCI secrets for region and tenant
  See \fBgoat oracle vault secrets-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBdelete\fP
  menu-guided solution to delete OCI secrets...
  See \fBgoat oracle vault secrets-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBshow\fP
  show the secrets stored in cache
  See \fBgoat oracle vault secrets-show(1)\fP for full documentation on the \fBshow\fP command.
