.TH "GOAT AMAZON SHOW" "1" "2024-02-04" "2024.2.4.728" "goat amazon show Manual"
.SH NAME
goat\-amazon\-show \- display configuration data for awstools...
.SH SYNOPSIS
.B goat amazon show
[OPTIONS] {all_config|buckets|instances|public_ips|regions|all_cached|aws_config|aws_credentials|orphaned_ebs}
.SH DESCRIPTION
display configuration data for awstools and awscli
