.TH "GOAT OCI COMPARTMENT DELETE" "1" "2023-09-21" "2023.9.20.2226" "goat oci compartment delete Manual"
.SH NAME
goat\-oci\-compartment\-delete \- menu-guided solution to delete OCI...
.SH SYNOPSIS
.B goat oci compartment delete
[OPTIONS]
.SH DESCRIPTION
menu-guided solution to delete OCI compartment's for region and tenant
