.TH "GOAT AZDEV BOARDS FIND" "1" "2024-01-30" "2024.1.25.554" "goat azdev boards find Manual"
.SH NAME
goat\-azdev\-boards\-find \- search boards and sprints
.SH SYNOPSIS
.B goat azdev boards find
[OPTIONS]
.SH DESCRIPTION
search boards and sprints
.SH OPTIONS
.TP
\fB\-t,\fP \-\-team TEXT
provide team name for board search  [default: Infrastructure Engineering and Operations]
.TP
\fB\-b,\fP \-\-board TEXT
provide sprint board to search - default is current sprint
.TP
\fB\-j,\fP \-\-json
output results in JSON format  [default: False]
.TP
\fB\-o,\fP \-\-orderby TEXT
choose which field to use for sorting
.TP
\fB\-A,\fP \-\-ascending
show issues in ascending order  [default: False]
.TP
\fB\-D,\fP \-\-descending
show issues in descending order  [default: False]
.TP
\fB\-c,\fP \-\-csv TEXT
name of the csv file to save the results to
.TP
\fB\-a,\fP \-\-assignee TEXT
retrieve work items from board and filter by assignee
.TP
\fB\-r,\fP \-\-reporter TEXT
retrieve work items from board and filter by reporter
.TP
\fB\-s,\fP \-\-state TEXT
retrieve work items from board and filter by state
