.TH "GOAT AWS IAM" "1" "2023-09-21" "2023.9.20.2226" "goat aws iam Manual"
.SH NAME
goat\-aws\-iam \- manage and switch between AWS profiles in...
.SH SYNOPSIS
.B goat aws iam
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage and switch between AWS profiles in GC and SIM regions
.SH COMMANDS
.PP
\fBauthenticate\fP
  login using existing IAM creds or add new...
  See \fBgoat aws iam-authenticate(1)\fP for full documentation on the \fBauthenticate\fP command.
