.TH "GOAT ORACLE OSS DOWNLOAD" "1" "2024-02-04" "2024.2.4.728" "goat oracle oss download Manual"
.SH NAME
goat\-oracle\-oss\-download \- download from OSS to local storage
.SH SYNOPSIS
.B goat oracle oss download
[OPTIONS] [SOURCE]
.SH DESCRIPTION
download from OSS to local storage
.SH OPTIONS
.TP
\fB\-\-destination\fP TEXT
provide a local destination for download  [default: /Users/stacksc]
