.TH "GOAT SLACK CHANNEL ARCHIVE" "1" "2024-02-04" "2024.2.4.728" "goat slack channel archive Manual"
.SH NAME
goat\-slack\-channel\-archive \- set channel status to "archived"
.SH SYNOPSIS
.B goat slack channel archive
[OPTIONS]
.SH DESCRIPTION
set channel status to "archived"
.SH OPTIONS
.TP
\fB\-i,\fP \-\-id TEXT
target channel
