.TH "GOAT JENKINS SHOW JOBS CONSOLE" "1" "2024-02-04" "2024.2.4.728" "goat jenkins show jobs console Manual"
.SH NAME
goat\-jenkins\-show\-jobs\-console \- show console output of a specific job...
.SH SYNOPSIS
.B goat jenkins show jobs console
[OPTIONS] [NAME]
.SH DESCRIPTION
show console output of a specific job build number from jenkins
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
