.TH "GOAT OCI VAULT SECRETS CREATE" "1" "2023-09-21" "2023.9.20.2226" "goat oci vault secrets create Manual"
.SH NAME
goat\-oci\-vault\-secrets\-create \- create OCI secrets for region and tenant
.SH SYNOPSIS
.B goat oci vault secrets create
[OPTIONS]
.SH DESCRIPTION
create OCI secrets for region and tenant
.SH OPTIONS
.TP
\fB\-n,\fP \-\-name TEXT
secret name  [required]
.TP
\fB\-d,\fP \-\-description TEXT
short description for the secret; default uses the name of the secret as the description
.TP
\fB\-c,\fP \-\-content TEXT
secret content; default creates a random 16 character password
