.TH "GOAT IBM EXTRACT" "1" "2024-02-04" "2024.2.4.728" "goat ibm extract Manual"
.SH NAME
goat\-ibm\-extract \- extract the command tree for IBM CLI
.SH SYNOPSIS
.B goat ibm extract
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
extract the command tree for IBM CLI
.SH COMMANDS
.PP
\fBcommands\fP
  manually refresh the IBM CLI command tree
  See \fBgoat ibm extract-commands(1)\fP for full documentation on the \fBcommands\fP command.
