.TH "GOAT JENKINS SHOW USER DETAILS" "1" "2023-08-06" "1.0.0" "goat jenkins show user details Manual"
.SH NAME
goat\-jenkins\-show\-user\-details \- display user details for a selected user...
.SH SYNOPSIS
.B goat jenkins show user details
[OPTIONS] [NAME]
.SH DESCRIPTION
display user details for a selected user from Jenkins
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
