.TH "GOAT JENKINS SHOW USER" "1" "2023-08-06" "1.0.0" "goat jenkins show user Manual"
.SH NAME
goat\-jenkins\-show\-user \- display information about Jenkins users
.SH SYNOPSIS
.B goat jenkins show user
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
display information about Jenkins users
.SH COMMANDS
.PP
\fBdetails\fP
  display user details for a selected user...
  See \fBgoat jenkins show user-details(1)\fP for full documentation on the \fBdetails\fP command.
.PP
\fBwho\fP
  display list of users from Jenkins
  See \fBgoat jenkins show user-who(1)\fP for full documentation on the \fBwho\fP command.
.PP
\fBwhoami\fP
  simple LDAP verification against Jenkins
  See \fBgoat jenkins show user-whoami(1)\fP for full documentation on the \fBwhoami\fP command.
