.TH "GOAT OCI VAULT DELETE" "1" "2023-09-21" "2023.9.20.2226" "goat oci vault delete Manual"
.SH NAME
goat\-oci\-vault\-delete \- menu-guided solution to delete OCI vault's...
.SH SYNOPSIS
.B goat oci vault delete
[OPTIONS]
.SH DESCRIPTION
menu-guided solution to delete OCI vault's for region and tenant
.SH OPTIONS
.TP
\fB\-a,\fP \-\-all
delete all vaults found  [default: False]
