.TH "GOAT OVHAI" "1" "2024-01-24" "2024.1.19.237" "goat ovhai Manual"
.SH NAME
goat\-ovhai \- OVHAI CLI Client[35GCurrent Profile:...
.SH SYNOPSIS
.B goat ovhai
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
OVHAI CLI Client[35GCurrent Profile: [0;32m[4mDEFAULT[0m Region: [0;32m[4mN/A[0m
.SH COMMANDS
.PP
\fBextract\fP
  extract the command tree for OVHAI CLI
  See \fBgoat ovhai-extract(1)\fP for full documentation on the \fBextract\fP command.
