.TH "GOAT JIRA ISSUE REVIEW" "1" "2023-08-06" "1.0.0" "goat jira issue review Manual"
.SH NAME
goat\-jira\-issue\-review \- change the VMC Ops Review to Yes or No for...
.SH SYNOPSIS
.B goat jira issue review
[OPTIONS] ISSUE_KEY...
.SH DESCRIPTION
change the VMC Ops Review to Yes or No for a JIRA issue
.SH OPTIONS
.TP
\fB\-v,\fP \-\-value [Yes|No]
value to be used  [required]
