.TH "GOAT JIRA ISSUE ASSIGN" "1" "2023-09-21" "2023.9.20.2226" "goat jira issue assign Manual"
.SH NAME
goat\-jira\-issue\-assign \- change assignee of a given JIRA issue(s)
.SH SYNOPSIS
.B goat jira issue assign
[OPTIONS] ISSUE_KEYS...
.SH DESCRIPTION
change assignee of a given JIRA issue(s)
.SH OPTIONS
.TP
\fB\-a,\fP \-\-assignee TEXT
assignee name, i.e. stacksc
