.TH "GOAT ORACLE REGIONS" "1" "2024-02-04" "2024.2.4.728" "goat oracle regions Manual"
.SH NAME
goat\-oracle\-regions \- module to manage region subscriptions
.SH SYNOPSIS
.B goat oracle regions
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
module to manage region subscriptions
.SH OPTIONS
.TP
\fB\-m,\fP \-\-menu
use the menu to perform region actions  [default: False]
.SH COMMANDS
.PP
\fBrefresh\fP
  manually refresh regions cached data
  See \fBgoat oracle regions-refresh(1)\fP for full documentation on the \fBrefresh\fP command.
.PP
\fBshow\fP
  show the data stored in cached regions
  See \fBgoat oracle regions-show(1)\fP for full documentation on the \fBshow\fP command.
