.TH "GOAT OCI COMPARTMENT CREATE" "1" "2023-09-21" "2023.9.20.2226" "goat oci compartment create Manual"
.SH NAME
goat\-oci\-compartment\-create \- create OCI compartment for region and tenant
.SH SYNOPSIS
.B goat oci compartment create
[OPTIONS] COMPARTMENT
.SH DESCRIPTION
create OCI compartment for region and tenant
.SH OPTIONS
.TP
\fB\-d,\fP \-\-description TEXT
provide a short description for the new compartment
