.TH "GOAT SLACK CHANNEL CREATE" "1" "2023-09-21" "2023.9.20.2226" "goat slack channel create Manual"
.SH NAME
goat\-slack\-channel\-create \- create a new slack channel
.SH SYNOPSIS
.B goat slack channel create
[OPTIONS]
.SH DESCRIPTION
create a new slack channel
.SH OPTIONS
.TP
\fB\-n,\fP \-\-name TEXT
name for the new channel
.TP
\fB\-p,\fP \-\-private BOOLEAN
should the new channel be private
