.TH "GOAT JENKINS SHOW USER WHOAMI" "1" "2023-08-06" "1.0.0" "goat jenkins show user whoami Manual"
.SH NAME
goat\-jenkins\-show\-user\-whoami \- simple LDAP verification against Jenkins
.SH SYNOPSIS
.B goat jenkins show user whoami
[OPTIONS]
.SH DESCRIPTION
simple LDAP verification against Jenkins
