.TH "GOAT JENKINS" "1" "2023-08-06" "1.0.0" "goat jenkins Manual"
.SH NAME
goat\-jenkins \- Jenkins Client[40GCurrent Profile:...
.SH SYNOPSIS
.B goat jenkins
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Jenkins Client[40GCurrent Profile: [0;32m[4mDEFAULT[0m
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-p,\fP \-\-profile TEXT
user profile for Jenkins operations
.SH COMMANDS
.PP
\fBauth\fP
  perform authentication operations against...
  See \fBgoat jenkins-auth(1)\fP for full documentation on the \fBauth\fP command.
.PP
\fBshow\fP
  retrieve information from Jenkins
  See \fBgoat jenkins-show(1)\fP for full documentation on the \fBshow\fP command.
