.TH "GOAT AMAZON EC2 DELETE ORPHANED_EBS" "1" "2024-02-04" "2024.2.4.728" "goat amazon ec2 delete orphaned_ebs Manual"
.SH NAME
goat\-amazon\-ec2\-delete\-orphaned_ebs \- delete orphaned EBS volumes or snapshots
.SH SYNOPSIS
.B goat amazon ec2 delete orphaned_ebs
[OPTIONS]
.SH DESCRIPTION
delete orphaned EBS volumes or snapshots
.SH OPTIONS
.TP
\fB\-v,\fP \-\-volume
flag to delete orphaned EBS volumes
.TP
\fB\-s,\fP \-\-snapshot
flag to delete orphaned EBS snapshots
