.TH "GOAT ORACLE CLI" "1" "2024-02-04" "2024.2.4.728" "goat oracle cli Manual"
.SH NAME
goat\-oracle\-cli \- run any ocicli (oci) command while...
.SH SYNOPSIS
.B goat oracle cli
[OPTIONS] [OCICLI_COMMAND]...
.SH DESCRIPTION
run any ocicli (oci) command while leveraging ocitools profile functionality; append --help for usage on cli commands
.SH OPTIONS
.TP
\fB\-r,\fP \-\-region TEXT
OCI region to authenticate against
.TP
\fB\-i,\fP \-\-interactive
spawn the interactive shell
