.TH "GOAT AMAZON EC2 REFRESH" "1" "2024-02-04" "2024.2.4.728" "goat amazon ec2 refresh Manual"
.SH NAME
goat\-amazon\-ec2\-refresh \- manually refresh ec2 cached data
.SH SYNOPSIS
.B goat amazon ec2 refresh
[OPTIONS] [[all|instances|public_ips|regions|auto]]
.SH DESCRIPTION
manually refresh ec2 cached data
