.TH "GOAT JENKINS SHOW JOBS CONFIG" "1" "2024-02-04" "2024.2.4.728" "goat jenkins show jobs config Manual"
.SH NAME
goat\-jenkins\-show\-jobs\-config \- show XML configuration of a specific job...
.SH SYNOPSIS
.B goat jenkins show jobs config
[OPTIONS] [NAME]
.SH DESCRIPTION
show XML configuration of a specific job from jenkins
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
