.TH "GOAT AZ" "1" "2024-01-24" "2024.1.19.237" "goat az Manual"
.SH NAME
goat\-az \- AZ CLI Client[35GCurrent Profile:...
.SH SYNOPSIS
.B goat az
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
AZ CLI Client[35GCurrent Profile: [0;32m[4mDEFAULT[0m Region: [0;32m[4mUSWEST2[0m
.SH COMMANDS
.PP
\fBextract\fP
  extract the command tree for Azure CLI
  See \fBgoat az-extract(1)\fP for full documentation on the \fBextract\fP command.
