.TH "GOAT OCI EXTRACT" "1" "2024-01-24" "2024.1.19.237" "goat oci extract Manual"
.SH NAME
goat\-oci\-extract \- extract the command tree for OCI CLI
.SH SYNOPSIS
.B goat oci extract
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
extract the command tree for OCI CLI
.SH COMMANDS
.PP
\fBcommands\fP
  manually refresh the OCI CLI command tree
  See \fBgoat oci extract-commands(1)\fP for full documentation on the \fBcommands\fP command.
