.TH "GOAT JIRA PROJECT" "1" "2023-09-21" "2023.9.20.2226" "goat jira project Manual"
.SH NAME
goat\-jira\-project \- manage JIRA projects
.SH SYNOPSIS
.B goat jira project
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage JIRA projects
.SH COMMANDS
.PP
\fBsearch\fP
  show a summary of projects matching the...
  See \fBgoat jira project-search(1)\fP for full documentation on the \fBsearch\fP command.
