.TH "GOAT OCI CLI" "1" "2024-01-24" "2024.1.19.237" "goat oci cli Manual"
.SH NAME
goat\-oci\-cli \- run any ocicli (oci) command while...
.SH SYNOPSIS
.B goat oci cli
[OPTIONS] [OCICLI_COMMAND]...
.SH DESCRIPTION
run any ocicli (oci) command while leveraging ocitools profile functionality; append --help for usage on cli commands
.SH OPTIONS
.TP
\fB\-r,\fP \-\-region TEXT
OCI region to authenticate against
.TP
\fB\-i,\fP \-\-interactive
spawn the interactive shell
