.TH "GOAT ORACLE VAULT SECRETS DELETE" "1" "2024-02-04" "2024.2.4.728" "goat oracle vault secrets delete Manual"
.SH NAME
goat\-oracle\-vault\-secrets\-delete \- menu-guided solution to delete OCI secrets...
.SH SYNOPSIS
.B goat oracle vault secrets delete
[OPTIONS]
.SH DESCRIPTION
menu-guided solution to delete OCI secrets for region and tenant
.SH OPTIONS
.TP
\fB\-a,\fP \-\-all
delete all secrets found  [default: False]
