.TH "GOAT OCI VAULT SECRETS SHOW" "1" "2023-09-21" "2023.9.20.2226" "goat oci vault secrets show Manual"
.SH NAME
goat\-oci\-vault\-secrets\-show \- show the secrets stored in cache
.SH SYNOPSIS
.B goat oci vault secrets show
[OPTIONS] [SECRET]
.SH DESCRIPTION
show the secrets stored in cache
.SH OPTIONS
.TP
\fB\-d,\fP \-\-decrypt
decrypt secret content of type base64  [default: False]
