.TH "GOAT CONFIGS ADD" "1" "2023-08-06" "1.0.0" "goat configs add Manual"
.SH NAME
goat\-configs\-add \- add data to a configstore
.SH SYNOPSIS
.B goat configs add
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
add data to a configstore
.SH COMMANDS
.PP
\fBprofile\fP
  add a profile to a configstore
  See \fBgoat configs add-profile(1)\fP for full documentation on the \fBprofile\fP command.
.PP
\fBproperty\fP
  add a record to a profile stored in a...
  See \fBgoat configs add-property(1)\fP for full documentation on the \fBproperty\fP command.
