.TH "GOAT JENKINS SHOW JOBS INFO" "1" "2023-08-06" "1.0.0" "goat jenkins show jobs info Manual"
.SH NAME
goat\-jenkins\-show\-jobs\-info \- show details for a specific build and job...
.SH SYNOPSIS
.B goat jenkins show jobs info
[OPTIONS] [NAME]
.SH DESCRIPTION
show details for a specific build and job name in jenkins
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
