.TH "GOAT JENKINS" "1" "2023-09-21" "2023.9.20.2226" "goat jenkins Manual"
.SH NAME
goat\-jenkins \- Jenkins Client[35GCurrent Profile:...
.SH SYNOPSIS
.B goat jenkins
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Jenkins Client[35GCurrent Profile: [0;32m[4mHTTP://127.0.0.1:8080[0m
.SH OPTIONS
.TP
\fB\-p,\fP \-\-profile TEXT
user profile for Jenkins operations
.SH COMMANDS
.PP
\fBauth\fP
  perform authentication operations against...
  See \fBgoat jenkins-auth(1)\fP for full documentation on the \fBauth\fP command.
.PP
\fBshow\fP
  retrieve information from Jenkins
  See \fBgoat jenkins-show(1)\fP for full documentation on the \fBshow\fP command.
