.TH "GOAT OVHAI EXTRACT COMMANDS" "1" "2024-01-24" "2024.1.19.237" "goat ovhai extract commands Manual"
.SH NAME
goat\-ovhai\-extract\-commands \- manually refresh the OVHAI CLI command tree
.SH SYNOPSIS
.B goat ovhai extract commands
[OPTIONS]
.SH DESCRIPTION
manually refresh the OVHAI CLI command tree
