.TH "GOAT AZDEV ISSUE" "1" "2024-02-04" "2024.2.4.728" "goat azdev issue Manual"
.SH NAME
goat\-azdev\-issue \- manage Azure DevOps worklist items
.SH SYNOPSIS
.B goat azdev issue
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage Azure DevOps worklist items
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-m,\fP \-\-menu
launch a menu driven interface for common actions
.SH COMMANDS
.PP
\fBsearch\fP
  show a summary of specified issue or issues
  See \fBgoat azdev issue-search(1)\fP for full documentation on the \fBsearch\fP command.
