.TH "GOAT OCI IAM" "1" "2023-09-21" "2023.9.20.2226" "goat oci iam Manual"
.SH NAME
goat\-oci\-iam \- manage and switch between OCI profiles for...
.SH SYNOPSIS
.B goat oci iam
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage and switch between OCI profiles for all realms
.SH COMMANDS
.PP
\fBauthenticate\fP
  login using existing IAM creds or add new...
  See \fBgoat oci iam-authenticate(1)\fP for full documentation on the \fBauthenticate\fP command.
