.TH "GOAT JIRA ISSUE EXTRACT" "1" "2023-08-06" "1.0.0" "goat jira issue extract Manual"
.SH NAME
goat\-jira\-issue\-extract \- look for specific data in the description...
.SH SYNOPSIS
.B goat jira issue extract
[OPTIONS] ISSUE_KEYS...
.SH DESCRIPTION
look for specific data in the description of a given issue
.SH OPTIONS
.TP
\fB\-k,\fP \-\-key TEXT
data key to lookup  [required]
.TP
\fB\-e,\fP \-\-exact
only grab exact matches
