.TH "GOAT ORACLE IAM" "1" "2024-02-04" "2024.2.4.728" "goat oracle iam Manual"
.SH NAME
goat\-oracle\-iam \- manage and switch between OCI profiles for...
.SH SYNOPSIS
.B goat oracle iam
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage and switch between OCI profiles for all realms
.SH COMMANDS
.PP
\fBauthenticate\fP
  login using existing IAM creds or add new...
  See \fBgoat oracle iam-authenticate(1)\fP for full documentation on the \fBauthenticate\fP command.
