.TH "GOAT SLACK UNPOST" "1" "2023-09-21" "2023.9.20.2226" "goat slack unpost Manual"
.SH NAME
goat\-slack\-unpost \- delete a meessage in a given channel
.SH SYNOPSIS
.B goat slack unpost
[OPTIONS] CHANNEL...
.SH DESCRIPTION
delete a meessage in a given channel
.SH OPTIONS
.TP
\fB\-t,\fP \-\-timestamp TEXT
Text to include in the message  [required]
