.TH "GOAT ORACLE VAULT SECRETS SHOW" "1" "2024-02-04" "2024.2.4.728" "goat oracle vault secrets show Manual"
.SH NAME
goat\-oracle\-vault\-secrets\-show \- show the secrets stored in cache
.SH SYNOPSIS
.B goat oracle vault secrets show
[OPTIONS] [SECRET]
.SH DESCRIPTION
show the secrets stored in cache
.SH OPTIONS
.TP
\fB\-d,\fP \-\-decrypt
decrypt secret content of type base64  [default: False]
