.TH "GOAT CONFIGS SHOW" "1" "2023-09-21" "2023.9.20.2226" "goat configs show Manual"
.SH NAME
goat\-configs\-show \- show records stored in a configstore; you...
.SH SYNOPSIS
.B goat configs show
[OPTIONS]
.SH DESCRIPTION
show records stored in a configstore; you can use profile and record names to narrow down the results
.SH OPTIONS
.TP
\fB\-n,\fP \-\-name TEXT
name of the configstore to use  [required]
