.TH "GOAT JENKINS SHOW JOBS URLS" "1" "2023-09-21" "2023.9.20.2226" "goat jenkins show jobs urls Manual"
.SH NAME
goat\-jenkins\-show\-jobs\-urls \- show last 100 build urls for a specific...
.SH SYNOPSIS
.B goat jenkins show jobs urls
[OPTIONS] [NAME]
.SH DESCRIPTION
show last 100 build urls for a specific job in jenkins
