.TH "GOAT SLACK REACT" "1" "2024-02-04" "2024.2.4.728" "goat slack react Manual"
.SH NAME
goat\-slack\-react \- post a reaction to a given message in...
.SH SYNOPSIS
.B goat slack react
[OPTIONS] CHANNEL...
.SH DESCRIPTION
post a reaction to a given message in specific channel
.SH OPTIONS
.TP
\fB\-t,\fP \-\-timestamp TEXT
timestamp of the target message  [required]
.TP
\fB\-e,\fP \-\-emoji TEXT
emoji name to react with  [required]
