.TH "GOAT ORACLE COMPARTMENT DELETE" "1" "2024-02-04" "2024.2.4.728" "goat oracle compartment delete Manual"
.SH NAME
goat\-oracle\-compartment\-delete \- menu-guided solution to delete OCI...
.SH SYNOPSIS
.B goat oracle compartment delete
[OPTIONS]
.SH DESCRIPTION
menu-guided solution to delete OCI compartment's for region and tenant
