.TH "GOAT AMAZON IAM" "1" "2024-02-04" "2024.2.4.728" "goat amazon iam Manual"
.SH NAME
goat\-amazon\-iam \- manage and switch between AWS profiles in...
.SH SYNOPSIS
.B goat amazon iam
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage and switch between AWS profiles in GC and SIM regions
.SH COMMANDS
.PP
\fBauthenticate\fP
  login using existing IAM creds or add new...
  See \fBgoat amazon iam-authenticate(1)\fP for full documentation on the \fBauthenticate\fP command.
