.TH "GOAT IBMCLOUD" "1" "2024-01-24" "2024.1.19.237" "goat ibmcloud Manual"
.SH NAME
goat\-ibmcloud \- IBMCLOUD CLI Client[35GCurrent Profile:...
.SH SYNOPSIS
.B goat ibmcloud
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
IBMCLOUD CLI Client[35GCurrent Profile: [0;32m[4mDEFAULT[0m Region: [0;32m[4mN/A[0m
.SH COMMANDS
.PP
\fBextract\fP
  extract the command tree for IBM CLI
  See \fBgoat ibmcloud-extract(1)\fP for full documentation on the \fBextract\fP command.
