.TH "GOAT CONFIGS DELETE" "1" "2023-08-06" "1.0.0" "goat configs delete Manual"
.SH NAME
goat\-configs\-delete \- delete data saved in a configstore
.SH SYNOPSIS
.B goat configs delete
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
delete data saved in a configstore
.SH COMMANDS
.PP
\fBprofile\fP
  delete an entire profile stored in a...
  See \fBgoat configs delete-profile(1)\fP for full documentation on the \fBprofile\fP command.
.PP
\fBproperty\fP
  delete a record stored in a configstore
  See \fBgoat configs delete-property(1)\fP for full documentation on the \fBproperty\fP command.
