.TH "GOAT AZDEV SHOW ACCESS-TOKEN" "1" "2024-02-04" "2024.2.4.728" "goat azdev show access-token Manual"
.SH NAME
goat\-azdev\-show\-access-token \- API token for accessing the Jenins...
.SH SYNOPSIS
.B goat azdev show access-token
[OPTIONS]
.SH DESCRIPTION
API token for accessing the Jenins functionality
