.TH "GOAT OCI OSS UPLOAD" "1" "2023-09-21" "2023.9.20.2226" "goat oci oss upload Manual"
.SH NAME
goat\-oci\-oss\-upload \- upload from local storage to OSS bucket
.SH SYNOPSIS
.B goat oci oss upload
[OPTIONS] [DESTINATION]
.SH DESCRIPTION
upload from local storage to OSS bucket
.SH OPTIONS
.TP
\fB\-\-source\fP TEXT
provide a local source for upload  [required]
