.TH "GOAT ORACLE COMPUTE SHOW" "1" "2024-02-04" "2024.2.4.728" "goat oracle compute show Manual"
.SH NAME
goat\-oracle\-compute\-show \- show the data stored in compute cache...
.SH SYNOPSIS
.B goat oracle compute show
[OPTIONS] [[all|instances|public_ips|regions|orphaned_ebs|orphaned_snaps]]
.SH DESCRIPTION
show the data stored in compute cache (instacnes, IPs, regions)
