.TH "GOAT JENKINS SHOW CRUMB-TOKEN-AGE" "1" "2023-08-06" "1.0.0" "goat jenkins show crumb-token-age Manual"
.SH NAME
goat\-jenkins\-show\-crumb-token-age \- how long the current crumb token will...
.SH SYNOPSIS
.B goat jenkins show crumb-token-age
[OPTIONS]
.SH DESCRIPTION
how long the current crumb token will remain active
