.TH "PYPS CSP ORG USER ADD" "1" "2023-04-14" "1.0.0" "pyps csp org user add Manual"
.SH NAME
pyps\-csp\-org\-user\-add \- add user to a CSP org
.SH SYNOPSIS
.B pyps csp org user add
[OPTIONS] [USER_NAME]
.SH DESCRIPTION
add user to a CSP org
.SH OPTIONS
.TP
\fB\-r,\fP \-\-role [member|operator|owner]
provide a target role level  [required]
.TP
\fB\-o,\fP \-\-org TEXT
provide a target org to add a user to
