.TH "PYPS K8S DEPLOYMENTS" "1" "2023-01-01" "1.0.0" "pyps k8s deployments Manual"
.SH NAME
pyps\-k8s\-deployments \- manage and list deployments
.SH SYNOPSIS
.B pyps k8s deployments
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage and list deployments
.SH COMMANDS
.PP
\fBshow\fP
  show info about a specific deployment or...
  See \fBpyps k8s deployments-show(1)\fP for full documentation on the \fBshow\fP command.
