.TH "PYPS VMC ONBOARD" "1" "2023-04-14" "1.0.0" "pyps vmc onboard Manual"
.SH NAME
pyps\-vmc\-onboard \- VMC end-to-end customer onboarding tasks
.SH SYNOPSIS
.B pyps vmc onboard
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
VMC end-to-end customer onboarding tasks
.SH COMMANDS
.PP
\fBmenu\fP
  launch a menu to perform customer...
  See \fBpyps vmc onboard-menu(1)\fP for full documentation on the \fBmenu\fP command.
