.TH "PYPS IDP AUTH SETUP" "1" "2023-04-14" "1.0.0" "pyps idp auth setup Manual"
.SH NAME
pyps\-idp\-auth\-setup \- setup your API access to a given IDP tenancy
.SH SYNOPSIS
.B pyps idp auth setup
[OPTIONS]
.SH DESCRIPTION
setup your API access to a given IDP tenancy
.SH OPTIONS
.TP
\fB\-m,\fP \-\-manual
skip the menu interface
