.TH "PYPS VMC SDDC NSX SHOW VPN-INFO" "1" "2023-04-14" "1.0.0" "pyps vmc sddc nsx show vpn-info Manual"
.SH NAME
pyps\-vmc\-sddc\-nsx\-show\-vpn-info \- show vpn information for the SDDC
.SH SYNOPSIS
.B pyps vmc sddc nsx show vpn-info
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show vpn information for the SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
.TP
\fB\-t,\fP \-\-ticket TEXT
CSSD or CSCM ticket asssociated with the RTS task  [default: CSSD-1234]
.TP
\fB\-v,\fP \-\-vpn [L2|L3]
available VPN types are L2 or L3  [default: L2]
