.TH "PYPS VMC IDP SHOW" "1" "2023-04-14" "1.0.0" "pyps vmc idp show Manual"
.SH NAME
pyps\-vmc\-idp\-show \- list all vIDM tenants with optional filter
.SH SYNOPSIS
.B pyps vmc idp show
[OPTIONS]
.SH DESCRIPTION
list all vIDM tenants with optional filter
.SH OPTIONS
.TP
\fB\-t,\fP \-\-tenants
show only tenant display names
.TP
\fB\-f,\fP \-\-filter TEXT
filter the result by key:value, key: or :value
