.TH "PYPS VMC ORG PROPERTY" "1" "2023-04-14" "1.0.0" "pyps vmc org property Manual"
.SH NAME
pyps\-vmc\-org\-property \- manage org properties
.SH SYNOPSIS
.B pyps vmc org property
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage org properties
.SH COMMANDS
.PP
\fBdelete\fP
  delete a property from an org config | BROKEN
  See \fBpyps vmc org property-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBset\fP
  add a property to an org config
  See \fBpyps vmc org property-set(1)\fP for full documentation on the \fBset\fP command.
.PP
\fBdefault\fP
  add default set of properties to an org
  See \fBpyps vmc org property-default(1)\fP for full documentation on the \fBdefault\fP command.
