.TH "PYPS JENKINS SHOW CRUMB-TOKEN-AGE" "1" "2023-04-14" "1.0.0" "pyps jenkins show crumb-token-age Manual"
.SH NAME
pyps\-jenkins\-show\-crumb-token-age \- how long the current crumb token will...
.SH SYNOPSIS
.B pyps jenkins show crumb-token-age
[OPTIONS]
.SH DESCRIPTION
how long the current crumb token will remain active
