.TH "PYPS VMC SDDC SHOW ESX DETAILS" "1" "2023-04-14" "1.0.0" "pyps vmc sddc show esx details Manual"
.SH NAME
pyps\-vmc\-sddc\-show\-esx\-details \- show details about a specific ESXi host in...
.SH SYNOPSIS
.B pyps vmc sddc show esx details
[OPTIONS] [ESX_NAME] [SDDC_ID]
.SH DESCRIPTION
show details about a specific ESXi host in a specific SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
