.TH "PYPS K8S NODES SHOW OSSEC" "1" "2023-01-01" "1.0.0" "pyps k8s nodes show ossec Manual"
.SH NAME
pyps\-k8s\-nodes\-show\-ossec \- show the json files for ossec across all...
.SH SYNOPSIS
.B pyps k8s nodes show ossec
[OPTIONS] [CLUSTER_SHORT_NAME]
.SH DESCRIPTION
show the json files for ossec across all nodes
.SH OPTIONS
.TP
\fB\-m,\fP \-\-masters
run only against master nodes
.TP
\fB\-v,\fP \-\-var_only
display only vars
