.TH "PYPS AWS IAM RESET-PASSWORD" "1" "2023-04-14" "1.0.0" "pyps aws iam reset-password Manual"
.SH NAME
pyps\-aws\-iam\-reset-password \- reset and update IDP credentials in the...
.SH SYNOPSIS
.B pyps aws iam reset-password
[OPTIONS]
.SH DESCRIPTION
reset and update IDP credentials in the configstore
