.TH "PYPS CSP OAUTH PUBLISHER-ID" "1" "2023-04-14" "1.0.0" "pyps csp oauth publisher-id Manual"
.SH NAME
pyps\-csp\-oauth\-publisher-id \- create publisher-id for a specific app-id
.SH SYNOPSIS
.B pyps csp oauth publisher-id
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
create publisher-id for a specific app-id
.SH OPTIONS
.TP
\fB\-a,\fP \-\-app\-id TEXT
provide oauth-app ID
