.TH "PYPS SECRETS" "1" "2023-04-14" "1.0.0" "pyps secrets Manual"
.SH NAME
pyps\-secrets \- VMware Secrets Client[40GCurrent Profile:...
.SH SYNOPSIS
.B pyps secrets
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
VMware Secrets Client[40GCurrent Profile: [0;32m[4mAWS-VMC-SKS-POWERUSER[0m
.SH OPTIONS
.TP
\fB\-m,\fP \-\-menu
use the menu to perform secrets actions
.SH COMMANDS
.PP
\fBget-policy\fP
  get the secrets bucket policy to verify...
  See \fBpyps secrets-get-policy(1)\fP for full documentation on the \fBget-policy\fP command.
.PP
\fBset-policy\fP
  enable or disable VPC access to secrets...
  See \fBpyps secrets-set-policy(1)\fP for full documentation on the \fBset-policy\fP command.
.PP
\fBgenerate\fP
  generate password function to get a random...
  See \fBpyps secrets-generate(1)\fP for full documentation on the \fBgenerate\fP command.
.PP
\fBtoken-rotation\fP
  rotate tokens for a specific service/username
  See \fBpyps secrets-token-rotation(1)\fP for full documentation on the \fBtoken-rotation\fP command.
.PP
\fBupload\fP
  upload credential file to S3 secret bucket...
  See \fBpyps secrets-upload(1)\fP for full documentation on the \fBupload\fP command.
.PP
\fBdownload\fP
  download secrets from s3 to local storage
  See \fBpyps secrets-download(1)\fP for full documentation on the \fBdownload\fP command.
.PP
\fBshow\fP
  show secrets for a specific service from...
  See \fBpyps secrets-show(1)\fP for full documentation on the \fBshow\fP command.
