.TH "PYPS CSP OAUTH PATCH" "1" "2023-04-14" "1.0.0" "pyps csp oauth patch Manual"
.SH NAME
pyps\-csp\-oauth\-patch \- patch an oauth-app in CSP and set default...
.SH SYNOPSIS
.B pyps csp oauth patch
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
patch an oauth-app in CSP and set default roles
.SH OPTIONS
.TP
\fB\-a,\fP \-\-app\-id TEXT
provide oauth-app ID
