.TH "PYPS NEXUS AUTH" "1" "2023-04-14" "1.0.0" "pyps nexus auth Manual"
.SH NAME
pyps\-nexus\-auth \- perform authentication operations against...
.SH SYNOPSIS
.B pyps nexus auth
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
perform authentication operations against Nexus
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-u,\fP \-\-usage
provide usage instructions to setup access to Nexus tools
.SH COMMANDS
.PP
\fBsetup\fP
  setup your API access to nexus
  See \fBpyps nexus auth-setup(1)\fP for full documentation on the \fBsetup\fP command.
