.TH "PYPS VMC SHOW USER SESSIONS" "1" "2023-04-14" "1.0.0" "pyps vmc show user sessions Manual"
.SH NAME
pyps\-vmc\-show\-user\-sessions \- get max session limit for the user and...
.SH SYNOPSIS
.B pyps vmc show user sessions
[OPTIONS] [USER_ID] [TARGET_ORG]
.SH DESCRIPTION
get max session limit for the user and their active sessions
