.TH "PYPS AWS CLI" "1" "2023-04-14" "1.0.0" "pyps aws cli Manual"
.SH NAME
pyps\-aws\-cli \- run any awscli (aws) command while...
.SH SYNOPSIS
.B pyps aws cli
[OPTIONS] AWSCLI_COMMAND...
.SH DESCRIPTION
run any awscli (aws) command while leveraging awstools profile functionality
.SH OPTIONS
.TP
\fB\-r,\fP \-\-region TEXT
AWS region to authenticate against
