.TH "PYPS VMC SDDC POP CONNECT" "1" "2023-04-14" "1.0.0" "pyps vmc sddc pop connect Manual"
.SH NAME
pyps\-vmc\-sddc\-pop\-connect \- connect to POP associated with a specific...
.SH SYNOPSIS
.B pyps vmc sddc pop connect
[OPTIONS] SDDC_ID
.SH DESCRIPTION
connect to POP associated with a specific SDDC
