.TH "PYPS GIT SHOW GROUP" "1" "2023-03-07" "1.0.0" "pyps git show group Manual"
.SH NAME
pyps\-git\-show\-group \- list a specific group in Gitlab that you...
.SH SYNOPSIS
.B pyps git show group
[OPTIONS] [NAME]
.SH DESCRIPTION
list a specific group in Gitlab that you have access to
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
