.TH "PYPS VMC SHOW SDDC ESX" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc esx Manual"
.SH NAME
pyps\-vmc\-show\-sddc\-esx \- show data about the ESXi hosts in a SDDC
.SH SYNOPSIS
.B pyps vmc show sddc esx
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
show data about the ESXi hosts in a SDDC
.SH COMMANDS
.PP
\fBall\fP
  list ESXi hosts running under a given SDDC
  See \fBpyps vmc show sddc esx-all(1)\fP for full documentation on the \fBall\fP command.
.PP
\fBdetails\fP
  show details about a specific ESXi host in...
  See \fBpyps vmc show sddc esx-details(1)\fP for full documentation on the \fBdetails\fP command.
.PP
\fBcredentials\fP
  show login credentials for ESXi in a...
  See \fBpyps vmc show sddc esx-credentials(1)\fP for full documentation on the \fBcredentials\fP command.
.PP
\fBwitness\fP
  show VSAN witness host IP in a specific...
  See \fBpyps vmc show sddc esx-witness(1)\fP for full documentation on the \fBwitness\fP command.
