.TH "PYPS VMC SDDC NSX SHOW" "1" "2023-04-14" "1.0.0" "pyps vmc sddc nsx show Manual"
.SH NAME
pyps\-vmc\-sddc\-nsx\-show \- show data about the NSX in a SDDC
.SH SYNOPSIS
.B pyps vmc sddc nsx show
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
show data about the NSX in a SDDC
.SH COMMANDS
.PP
\fBsummary\fP
  quick summary of NSX related information...
  See \fBpyps vmc sddc nsx show-summary(1)\fP for full documentation on the \fBsummary\fP command.
.PP
\fBnode-status\fP
  show the node status for NSX in a specific...
  See \fBpyps vmc sddc nsx show-node-status(1)\fP for full documentation on the \fBnode-status\fP command.
.PP
\fBvpn-sessions\fP
  show the VPN sessions for NSX in a...
  See \fBpyps vmc sddc nsx show-vpn-sessions(1)\fP for full documentation on the \fBvpn-sessions\fP command.
.PP
\fBvpn-states\fP
  show the VPN session states for NSX in a...
  See \fBpyps vmc sddc nsx show-vpn-states(1)\fP for full documentation on the \fBvpn-states\fP command.
.PP
\fBvpn-endpoints\fP
  show the VPN local endpoints for NSX in a...
  See \fBpyps vmc sddc nsx show-vpn-endpoints(1)\fP for full documentation on the \fBvpn-endpoints\fP command.
.PP
\fBedge-status\fP
  show the edge status for NSX in a specific...
  See \fBpyps vmc sddc nsx show-edge-status(1)\fP for full documentation on the \fBedge-status\fP command.
.PP
\fBbgp-status\fP
  show the consolidated vpn bgp status for...
  See \fBpyps vmc sddc nsx show-bgp-status(1)\fP for full documentation on the \fBbgp-status\fP command.
.PP
\fBcluster-status\fP
  show the cluster status for NSX in a...
  See \fBpyps vmc sddc nsx show-cluster-status(1)\fP for full documentation on the \fBcluster-status\fP command.
.PP
\fBcredentials\fP
  show login credentials for NSX in a...
  See \fBpyps vmc sddc nsx show-credentials(1)\fP for full documentation on the \fBcredentials\fP command.
.PP
\fBvpn-info\fP
  show vpn information for the SDDC
  See \fBpyps vmc sddc nsx show-vpn-info(1)\fP for full documentation on the \fBvpn-info\fP command.
.PP
\fBnode-details\fP
  show standby edge information for the SDDC
  See \fBpyps vmc sddc nsx show-node-details(1)\fP for full documentation on the \fBnode-details\fP command.
.PP
\fBstandby-edge\fP
  show standby edge information for the SDDC
  See \fBpyps vmc sddc nsx show-standby-edge(1)\fP for full documentation on the \fBstandby-edge\fP command.
.PP
\fBactive-edge\fP
  show active edge information for the SDDC
  See \fBpyps vmc sddc nsx show-active-edge(1)\fP for full documentation on the \fBactive-edge\fP command.
.PP
\fBlogical-routers\fP
  show logical routers in a specific SDDC
  See \fBpyps vmc sddc nsx show-logical-routers(1)\fP for full documentation on the \fBlogical-routers\fP command.
