.TH "PYPS JENKINS SHOW USER WHOAMI" "1" "2023-04-14" "1.0.0" "pyps jenkins show user whoami Manual"
.SH NAME
pyps\-jenkins\-show\-user\-whoami \- simple LDAP verification against Jenkins
.SH SYNOPSIS
.B pyps jenkins show user whoami
[OPTIONS]
.SH DESCRIPTION
simple LDAP verification against Jenkins
