.TH "PYPS CSP ORG USER SESSION LIMIT" "1" "2023-04-14" "1.0.0" "pyps csp org user session limit Manual"
.SH NAME
pyps\-csp\-org\-user\-session\-limit \- change a user's active session limit
.SH SYNOPSIS
.B pyps csp org user session limit
[OPTIONS] USER_ID NEW_LIMIT
.SH DESCRIPTION
change a user's active session limit
