.TH "PYPS VMC SHOW ROLES" "1" "2023-04-14" "1.0.0" "pyps vmc show roles Manual"
.SH NAME
pyps\-vmc\-show\-roles \- show a summary of available VMC org roles
.SH SYNOPSIS
.B pyps vmc show roles
[OPTIONS]
.SH DESCRIPTION
show a summary of available VMC org roles
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
