.TH "PYPS VMC SDDC ESX SSH-TOGGLE" "1" "2023-04-14" "1.0.0" "pyps vmc sddc esx ssh-toggle Manual"
.SH NAME
pyps\-vmc\-sddc\-esx\-ssh-toggle \- enable or disable SSH on an ESXi host in a...
.SH SYNOPSIS
.B pyps vmc sddc esx ssh-toggle
[OPTIONS] {enable|disable} [SDDC_ID] [ESX_NAME]
.SH DESCRIPTION
enable or disable SSH on an ESXi host in a specific SDDC
.SH OPTIONS
.TP
\fB\-t,\fP \-\-ticket TEXT
CSSD or CSCM ticket asssociated with the RTS task  [default: CSSD-1234]
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
