.TH "PYPS IDP SHOW USERS" "1" "2023-04-14" "1.0.0" "pyps idp show users Manual"
.SH NAME
pyps\-idp\-show\-users \- retrieve all users from target tenant
.SH SYNOPSIS
.B pyps idp show users
[OPTIONS]
.SH DESCRIPTION
retrieve all users from target tenant
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
