.TH "PYPS VMC ACCOUNT SHOW ALL" "1" "2023-04-14" "1.0.0" "pyps vmc account show all Manual"
.SH NAME
pyps\-vmc\-account\-show\-all \- show all AWS accounts added to VMC
.SH SYNOPSIS
.B pyps vmc account show all
[OPTIONS]
.SH DESCRIPTION
show all AWS accounts added to VMC
.SH OPTIONS
.TP
\fB\-s,\fP \-\-state [ACTIVE|DELETED]
only list accounts in a specific state
.TP
\fB\-n,\fP \-\-numbers
limit the output to only aws account numbers
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
