.TH "PYPS VMC ACCOUNT DISASSOCIATE" "1" "2023-04-14" "1.0.0" "pyps vmc account disassociate Manual"
.SH NAME
pyps\-vmc\-account\-disassociate \- disassociate an AWS account with a VMC org
.SH SYNOPSIS
.B pyps vmc account disassociate
[OPTIONS] AWS_ACCOUNT_ID ORG_ID
.SH DESCRIPTION
disassociate an AWS account with a VMC org
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
