.TH "PYPS CSP SHOW USER USERID" "1" "2023-04-14" "1.0.0" "pyps csp show user userid Manual"
.SH NAME
pyps\-csp\-show\-user\-userid \- get userid for a specific user in CSP
.SH SYNOPSIS
.B pyps csp show user userid
[OPTIONS] [USER_NAME] [TARGET_ORG]
.SH DESCRIPTION
get userid for a specific user in CSP
