.TH "PYPS VMC SDDC SHOW NSX VPN-SESSIONS" "1" "2023-04-14" "1.0.0" "pyps vmc sddc show nsx vpn-sessions Manual"
.SH NAME
pyps\-vmc\-sddc\-show\-nsx\-vpn-sessions \- show the VPN sessions for NSX in a...
.SH SYNOPSIS
.B pyps vmc sddc show nsx vpn-sessions
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show the VPN sessions for NSX in a specific SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
