.TH "PYPS SLACK CHANNEL ARCHIVE" "1" "2023-03-03" "1.0.0" "pyps slack channel archive Manual"
.SH NAME
pyps\-slack\-channel\-archive \- set channel status to "archived"
.SH SYNOPSIS
.B pyps slack channel archive
[OPTIONS]
.SH DESCRIPTION
set channel status to "archived"
.SH OPTIONS
.TP
\fB\-i,\fP \-\-id TEXT
target channel
