.TH "PYPS VMC ORG SHOW FEATURES" "1" "2023-04-14" "1.0.0" "pyps vmc org show features Manual"
.SH NAME
pyps\-vmc\-org\-show\-features \- list enabled features for a CSP org
.SH SYNOPSIS
.B pyps vmc org show features
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
list enabled features for a CSP org
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
