.TH "PYPS SLACK UNPOST" "1" "2023-03-03" "1.0.0" "pyps slack unpost Manual"
.SH NAME
pyps\-slack\-unpost \- delete a meessage in a given channel
.SH SYNOPSIS
.B pyps slack unpost
[OPTIONS] CHANNEL...
.SH DESCRIPTION
delete a meessage in a given channel
.SH OPTIONS
.TP
\fB\-t,\fP \-\-timestamp TEXT
Text to include in the message  [required]
