.TH "PYPS FLY SHOW PIPELINES" "1" "2023-03-03" "1.0.0" "pyps fly show pipelines Manual"
.SH NAME
pyps\-fly\-show\-pipelines \- display pipelnes found in Concourse
.SH SYNOPSIS
.B pyps fly show pipelines
[OPTIONS]
.SH DESCRIPTION
display pipelnes found in Concourse
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
.TP
\fB\-p,\fP \-\-pattern TEXT
pattern to search on due to the number of pipelines
