.TH "PYPS K8S CLUSTER EVENTS" "1" "2023-01-01" "1.0.0" "pyps k8s cluster events Manual"
.SH NAME
pyps\-k8s\-cluster\-events \- show cluster events for a specific cluster...
.SH SYNOPSIS
.B pyps k8s cluster events
[OPTIONS] [CLUSTER_SHORT_NAME]
.SH DESCRIPTION
show cluster events for a specific cluster or all clusters
