.TH "PYPS K8S SHOW DEPLOYMENTS" "1" "2023-01-01" "1.0.0" "pyps k8s show deployments Manual"
.SH NAME
pyps\-k8s\-show\-deployments \- show info about a specific deployment or...
.SH SYNOPSIS
.B pyps k8s show deployments
[OPTIONS] [DEPLOYMENT]
.SH DESCRIPTION
show info about a specific deployment or all deployments
.SH OPTIONS
.TP
\fB\-c,\fP \-\-cluster TEXT
limit the search to a specific cluster (short name, ie. res002)
.TP
\fB\-n,\fP \-\-namespace TEXT
limit the search to a specific namespace
.TP
\fB\-a,\fP \-\-app TEXT
limit the search to a specific app
