.TH "PYPS VMC SHOW FEATURES" "1" "2023-04-14" "1.0.0" "pyps vmc show features Manual"
.SH NAME
pyps\-vmc\-show\-features \- show a summary of available VMC org features
.SH SYNOPSIS
.B pyps vmc show features
[OPTIONS]
.SH DESCRIPTION
show a summary of available VMC org features
.SH OPTIONS
.TP
\fB\-f,\fP \-\-filter TEXT
filter the result by key:value, key: or :value
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
