.TH "PYPS VMC SDDC DRAAS MANAGE DEACTIVATE" "1" "2023-04-14" "1.0.0" "pyps vmc sddc draas manage deactivate Manual"
.SH NAME
pyps\-vmc\-sddc\-draas\-manage\-deactivate \- deactivate site-recovery
.SH SYNOPSIS
.B pyps vmc sddc draas manage deactivate
[OPTIONS] [TARGET_ORG] [SDDC_ID]
.SH DESCRIPTION
deactivate site-recovery
.SH OPTIONS
.TP
\fB\-t,\fP \-\-ticket TEXT
[required]
