.TH "PYPS FLY ACTION" "1" "2023-03-03" "1.0.0" "pyps fly action Manual"
.SH NAME
pyps\-fly\-action \- action tasks for concourse runway
.SH SYNOPSIS
.B pyps fly action
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
action tasks for concourse runway
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-m,\fP \-\-menu
launch a menu driven interface for common CSP user actions
.SH COMMANDS
.PP
\fBtrigger\fP
  trigger a runway post-deploy job with it's...
  See \fBpyps fly action-trigger(1)\fP for full documentation on the \fBtrigger\fP command.
