.TH "PYPS VMC SDDC SHOW DRAAS DETAILS" "1" "2023-04-14" "1.0.0" "pyps vmc sddc show draas details Manual"
.SH NAME
pyps\-vmc\-sddc\-show\-draas\-details \- show details about draas
.SH SYNOPSIS
.B pyps vmc sddc show draas details
[OPTIONS] [TARGET_ORG] [SDDC_ID]
.SH DESCRIPTION
show details about draas
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
