.TH "PYPS VMC SHOW SDDC DRAAS PLAN" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc draas plan Manual"
.SH NAME
pyps\-vmc\-show\-sddc\-draas\-plan \- retrieve draas site-recovery plans for the...
.SH SYNOPSIS
.B pyps vmc show sddc draas plan
[OPTIONS] [TARGET_ORG] [SDDC_ID]
.SH DESCRIPTION
retrieve draas site-recovery plans for the specified SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
