.TH "PYPS JENKINS SHOW CREDENTIALS" "1" "2023-04-14" "1.0.0" "pyps jenkins show credentials Manual"
.SH NAME
pyps\-jenkins\-show\-credentials \- display system credentials available for jobs
.SH SYNOPSIS
.B pyps jenkins show credentials
[OPTIONS]
.SH DESCRIPTION
display system credentials available for jobs
.SH OPTIONS
.TP
\fB\-d,\fP \-\-description
display description of credentials in the output
