.TH "PYPS VMC SDDC NSX SHOW BGP-STATUS" "1" "2023-04-14" "1.0.0" "pyps vmc sddc nsx show bgp-status Manual"
.SH NAME
pyps\-vmc\-sddc\-nsx\-show\-bgp-status \- show the consolidated vpn bgp status for...
.SH SYNOPSIS
.B pyps vmc sddc nsx show bgp-status
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show the consolidated vpn bgp status for NSX in a specific SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
