.TH "PYPS SLACK CHANNEL CREATE" "1" "2023-03-03" "1.0.0" "pyps slack channel create Manual"
.SH NAME
pyps\-slack\-channel\-create \- create a new slack channel
.SH SYNOPSIS
.B pyps slack channel create
[OPTIONS]
.SH DESCRIPTION
create a new slack channel
.SH OPTIONS
.TP
\fB\-n,\fP \-\-name TEXT
name for the new channel
.TP
\fB\-p,\fP \-\-private BOOLEAN
should the new channel be private
