.TH "PYPS REPORT" "1" "2023-03-03" "1.0.0" "pyps report Manual"
.SH NAME
pyps\-report \- create reports for different systems
.SH SYNOPSIS
.B pyps report
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
create reports for different systems
.SH COMMANDS
.PP
\fBimage-promotion\fP
  attempt to pull Transaction-ID from a...
  See \fBpyps report-image-promotion(1)\fP for full documentation on the \fBimage-promotion\fP command.
