.TH "PYPS SECRETS TOKEN-ROTATION" "1" "2023-04-14" "1.0.0" "pyps secrets token-rotation Manual"
.SH NAME
pyps\-secrets\-token-rotation \- rotate tokens for a specific service/username
.SH SYNOPSIS
.B pyps secrets token-rotation
[OPTIONS]
.SH DESCRIPTION
rotate tokens for a specific service/username
.SH OPTIONS
.TP
\fB\-t,\fP \-\-ticket
create a JIRA ticket prior to rolling restart of services
.TP
\fB\-r,\fP \-\-restart
perform a rolling restart of services
