.TH "PYPS VMC SDDC SHOW VCENTER" "1" "2023-04-14" "1.0.0" "pyps vmc sddc show vcenter Manual"
.SH NAME
pyps\-vmc\-sddc\-show\-vcenter \- show data about the vCenter server in a SDDC
.SH SYNOPSIS
.B pyps vmc sddc show vcenter
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
show data about the vCenter server in a SDDC
.SH COMMANDS
.PP
\fBcredentials\fP
  show login credentials for the vCenter...
  See \fBpyps vmc sddc show vcenter-credentials(1)\fP for full documentation on the \fBcredentials\fP command.
.PP
\fBurl\fP
  show URLs for the vCenter server in a...
  See \fBpyps vmc sddc show vcenter-url(1)\fP for full documentation on the \fBurl\fP command.
