.TH "PYPS JENKINS" "1" "2023-04-14" "1.0.0" "pyps jenkins Manual"
.SH NAME
pyps\-jenkins \- VMware Jenkins Client[40GCurrent Profile:...
.SH SYNOPSIS
.B pyps jenkins
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
VMware Jenkins Client[40GCurrent Profile: [0;32m[4mATLAS[0m
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-p,\fP \-\-profile TEXT
user profile for Jenkins operations
.SH COMMANDS
.PP
\fBauth\fP
  perform authentication operations against...
  See \fBpyps jenkins-auth(1)\fP for full documentation on the \fBauth\fP command.
.PP
\fBshow\fP
  retrieve information from Jenkins
  See \fBpyps jenkins-show(1)\fP for full documentation on the \fBshow\fP command.
