.TH "PYPS VMC SDDC DRAAS MANAGE ACTIVATE" "1" "2023-04-14" "1.0.0" "pyps vmc sddc draas manage activate Manual"
.SH NAME
pyps\-vmc\-sddc\-draas\-manage\-activate \- activate site-recovery
.SH SYNOPSIS
.B pyps vmc sddc draas manage activate
[OPTIONS] [TARGET_ORG] [SDDC_ID]
.SH DESCRIPTION
activate site-recovery
