.TH "PYPS K8S NAMESPACES" "1" "2023-01-01" "1.0.0" "pyps k8s namespaces Manual"
.SH NAME
pyps\-k8s\-namespaces \- manage and list namespaces
.SH SYNOPSIS
.B pyps k8s namespaces
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage and list namespaces
.SH COMMANDS
.PP
\fBshow\fP
  list namespaces
  See \fBpyps k8s namespaces-show(1)\fP for full documentation on the \fBshow\fP command.
