.TH "PYPS CONFLUENCE" "1" "2023-03-03" "1.0.0" "pyps confluence Manual"
.SH NAME
pyps\-confluence \- VMware Confluence CLI Client -> Current...
.SH SYNOPSIS
.B pyps confluence
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
VMware Confluence CLI Client -> Current Profile: [0;32m[4mDEFAULT[0m
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-p,\fP \-\-profile TEXT
user profile for Confluence operations
.SH COMMANDS
.PP
\fBauth\fP
  perform authentication operations against...
  See \fBpyps confluence-auth(1)\fP for full documentation on the \fBauth\fP command.
.PP
\fBshow\fP
  retrieve information from Confluence
  See \fBpyps confluence-show(1)\fP for full documentation on the \fBshow\fP command.
