.TH "PYPS K8S" "1" "2023-01-01" "1.0.0" "pyps k8s Manual"
.SH NAME
pyps\-k8s \- IN-DEV | a tool to make kubernetes & vdp...
.SH SYNOPSIS
.B pyps k8s
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
IN-DEV | a tool to make kubernetes & vdp less of a pain
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-p,\fP \-\-profile TEXT
user profile for the operation
.SH COMMANDS
.PP
\fBvdp\fP
  a collection of utilities to help with VDP
  See \fBpyps k8s-vdp(1)\fP for full documentation on the \fBvdp\fP command.
.PP
\fBcluster\fP
  switch cluster contexts and show k8s...
  See \fBpyps k8s-cluster(1)\fP for full documentation on the \fBcluster\fP command.
.PP
\fBdeployments\fP
  manage and list deployments
  See \fBpyps k8s-deployments(1)\fP for full documentation on the \fBdeployments\fP command.
.PP
\fBnamespaces\fP
  manage and list namespaces
  See \fBpyps k8s-namespaces(1)\fP for full documentation on the \fBnamespaces\fP command.
.PP
\fBnodes\fP
  manage and list nodes
  See \fBpyps k8s-nodes(1)\fP for full documentation on the \fBnodes\fP command.
.PP
\fBshow\fP
  show information pulled from VDP/kubernetes
  See \fBpyps k8s-show(1)\fP for full documentation on the \fBshow\fP command.
