.TH "PYPS VMC SDDC DELETE" "1" "2023-04-14" "1.0.0" "pyps vmc sddc delete Manual"
.SH NAME
pyps\-vmc\-sddc\-delete \- delete a specific SDDC in a given org
.SH SYNOPSIS
.B pyps vmc sddc delete
[OPTIONS] TARGET_ORG SDDC_ID
.SH DESCRIPTION
delete a specific SDDC in a given org
.SH OPTIONS
.TP
\fB\-f,\fP \-\-force
force the deleton (if its stuck)
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
