.TH "PYPS VMC SHOW ORG ORG-ID" "1" "2023-04-14" "1.0.0" "pyps vmc show org org-id Manual"
.SH NAME
pyps\-vmc\-show\-org\-org-id \- lookup a CSP org ID using the name...
.SH SYNOPSIS
.B pyps vmc show org org-id
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
lookup a CSP org ID using the name configured for it in csptools
