.TH "PYPS K8S NODES DELETE" "1" "2023-01-01" "1.0.0" "pyps k8s nodes delete Manual"
.SH NAME
pyps\-k8s\-nodes\-delete \- delete a node in a specific cluster
.SH SYNOPSIS
.B pyps k8s nodes delete
[OPTIONS] [CLUSTER_SHORT_NAME] [NODE_NAME] COMMAND [ARGS]...
.SH DESCRIPTION
delete a node in a specific cluster
.SH OPTIONS
.TP
\fB\-f,\fP \-\-force
force the deletion
