.TH "PYPS K8S SHOW" "1" "2023-01-01" "1.0.0" "pyps k8s show Manual"
.SH NAME
pyps\-k8s\-show \- show information pulled from VDP/kubernetes
.SH SYNOPSIS
.B pyps k8s show
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
show information pulled from VDP/kubernetes
.SH COMMANDS
.PP
\fBvdp_clusters\fP
  show a list of VDP clusters
  See \fBpyps k8s show-vdp_clusters(1)\fP for full documentation on the \fBvdp_clusters\fP command.
.PP
\fBdeployments\fP
  show info about a specific deployment or...
  See \fBpyps k8s show-deployments(1)\fP for full documentation on the \fBdeployments\fP command.
.PP
\fBnamespaces\fP
  list namespaces
  See \fBpyps k8s show-namespaces(1)\fP for full documentation on the \fBnamespaces\fP command.
