.TH "PYPS JFROG SHOW REPO" "1" "2023-03-03" "1.0.0" "pyps jfrog show repo Manual"
.SH NAME
pyps\-jfrog\-show\-repo \- display packages per repository selected...
.SH SYNOPSIS
.B pyps jfrog show repo
[OPTIONS] [NAME]
.SH DESCRIPTION
display packages per repository selected in JFROG
.SH OPTIONS
.TP
\fB\-p,\fP \-\-pattern TEXT
.PP
