.TH "PYPS VMC ORG SHOW" "1" "2023-04-14" "1.0.0" "pyps vmc org show Manual"
.SH NAME
pyps\-vmc\-org\-show \- display info about CSP org(s)
.SH SYNOPSIS
.B pyps vmc org show
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
display info about CSP org(s)
.SH COMMANDS
.PP
\fBproperties\fP
  show VMC properties about a CSP org
  See \fBpyps vmc org show-properties(1)\fP for full documentation on the \fBproperties\fP command.
.PP
\fBall\fP
  show all CSP orgs registered in VMC
  See \fBpyps vmc org show-all(1)\fP for full documentation on the \fBall\fP command.
.PP
\fBfeatures\fP
  list enabled features for a CSP org
  See \fBpyps vmc org show-features(1)\fP for full documentation on the \fBfeatures\fP command.
.PP
\fBtags\fP
  list all tags for a CSP org
  See \fBpyps vmc org show-tags(1)\fP for full documentation on the \fBtags\fP command.
.PP
\fBtasks\fP
  show tasks for a CSP org
  See \fBpyps vmc org show-tasks(1)\fP for full documentation on the \fBtasks\fP command.
.PP
\fBdetails\fP
  show all details about a given org
  See \fBpyps vmc org show-details(1)\fP for full documentation on the \fBdetails\fP command.
.PP
\fBsddcs\fP
  show all sddcs deployed under a given org
  See \fBpyps vmc org show-sddcs(1)\fP for full documentation on the \fBsddcs\fP command.
.PP
\fBusers\fP
  list all users in an org
  See \fBpyps vmc org show-users(1)\fP for full documentation on the \fBusers\fP command.
.PP
\fBtask\fP
  show details about a specific task
  See \fBpyps vmc org show-task(1)\fP for full documentation on the \fBtask\fP command.
.PP
\fBrefresh-token\fP
  API refresh-token used for generating an...
  See \fBpyps vmc org show-refresh-token(1)\fP for full documentation on the \fBrefresh-token\fP command.
.PP
\fBaccess-token\fP
  API token for accessing the CSP functionality
  See \fBpyps vmc org show-access-token(1)\fP for full documentation on the \fBaccess-token\fP command.
.PP
\fBaccess-token-age\fP
  how long the current access token will...
  See \fBpyps vmc org show-access-token-age(1)\fP for full documentation on the \fBaccess-token-age\fP command.
.PP
\fBconfig\fP
  retrieve all stored config for an org
  See \fBpyps vmc org show-config(1)\fP for full documentation on the \fBconfig\fP command.
.PP
\fBorg-id\fP
  lookup a CSP org ID using the name...
  See \fBpyps vmc org show-org-id(1)\fP for full documentation on the \fBorg-id\fP command.
.PP
\fBorg-name\fP
  lookup a CSP org name (if configured)...
  See \fBpyps vmc org show-org-name(1)\fP for full documentation on the \fBorg-name\fP command.
.PP
\fBaccount\fP
  show details about AWS account associated...
  See \fBpyps vmc org show-account(1)\fP for full documentation on the \fBaccount\fP command.
