.TH "PYPS VMC SHOW SDDC DRAAS TASK" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc draas task Manual"
.SH NAME
pyps\-vmc\-show\-sddc\-draas\-task \- show details about a specific draas task-id
.SH SYNOPSIS
.B pyps vmc show sddc draas task
[OPTIONS] [TARGET_ORG] [TASK_ID]
.SH DESCRIPTION
show details about a specific draas task-id
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
