.TH "PYPS IDP" "1" "2023-04-14" "1.0.0" "pyps idp Manual"
.SH NAME
pyps\-idp \- VMware IDP CLI Client[40GCurrent Profile:...
.SH SYNOPSIS
.B pyps idp
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
VMware IDP CLI Client[40GCurrent Profile: [0;32m[4mVMC-PROD[0m
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-p,\fP \-\-profile TEXT
user profile for IDP/vIDP operations
.SH COMMANDS
.PP
\fBauth\fP
  perform authentication operations against...
  See \fBpyps idp-auth(1)\fP for full documentation on the \fBauth\fP command.
.PP
\fBshow\fP
  retrieve information from IDP/vIDP
  See \fBpyps idp-show(1)\fP for full documentation on the \fBshow\fP command.
.PP
\fBtenants\fP
  manage tenants
  See \fBpyps idp-tenants(1)\fP for full documentation on the \fBtenants\fP command.
.PP
\fBusers\fP
  manage users per tenant
  See \fBpyps idp-users(1)\fP for full documentation on the \fBusers\fP command.
