.TH "PYPS CSP ORG USER SHOW DETAILS" "1" "2023-04-14" "1.0.0" "pyps csp org user show details Manual"
.SH NAME
pyps\-csp\-org\-user\-show\-details \- list details about the user
.SH SYNOPSIS
.B pyps csp org user show details
[OPTIONS] [USER_NAME] [TARGET_ORG]
.SH DESCRIPTION
list details about the user
