.TH "PYPS VMC SHOW SDDC ESX ALL" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc esx all Manual"
.SH NAME
pyps\-vmc\-show\-sddc\-esx\-all \- list ESXi hosts running under a given SDDC
.SH SYNOPSIS
.B pyps vmc show sddc esx all
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
list ESXi hosts running under a given SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
