.TH "PYPS K8S NODES SHOW TOP" "1" "2023-01-01" "1.0.0" "pyps k8s nodes show top Manual"
.SH NAME
pyps\-k8s\-nodes\-show\-top \- show all the top nodes
.SH SYNOPSIS
.B pyps k8s nodes show top
[OPTIONS] [CLUSTER_SHORT_NAME]
.SH DESCRIPTION
show all the top nodes
.SH OPTIONS
.TP
\fB\-s,\fP \-\-sort [mem|cpu]
sort by cpu ot by memory
