.TH "PYPS JENKINS SHOW USER DETAILS" "1" "2023-04-14" "1.0.0" "pyps jenkins show user details Manual"
.SH NAME
pyps\-jenkins\-show\-user\-details \- display user details for a selected user...
.SH SYNOPSIS
.B pyps jenkins show user details
[OPTIONS] [NAME]
.SH DESCRIPTION
display user details for a selected user from Jenkins
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
