.TH "PYPS VMC ORG USER SESSION LIMIT" "1" "2023-04-14" "1.0.0" "pyps vmc org user session limit Manual"
.SH NAME
pyps\-vmc\-org\-user\-session\-limit \- change a user's active session limit
.SH SYNOPSIS
.B pyps vmc org user session limit
[OPTIONS] USER_ID NEW_LIMIT
.SH DESCRIPTION
change a user's active session limit
