.TH "PYPS VMC SHOW SDDC NSX NODE-STATUS" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc nsx node-status Manual"
.SH NAME
pyps\-vmc\-show\-sddc\-nsx\-node-status \- show the node status for NSX in a specific...
.SH SYNOPSIS
.B pyps vmc show sddc nsx node-status
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show the node status for NSX in a specific SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
