.TH "PYPS IDP TENANTS" "1" "2023-04-14" "1.0.0" "pyps idp tenants Manual"
.SH NAME
pyps\-idp\-tenants \- manage tenants
.SH SYNOPSIS
.B pyps idp tenants
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage tenants
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.SH COMMANDS
.PP
\fBcreate\fP
  create new child tenant
  See \fBpyps idp tenants-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBdelete\fP
  delete child tenant
  See \fBpyps idp tenants-delete(1)\fP for full documentation on the \fBdelete\fP command.
