.TH "PYPS IDP SHOW DIRECTORIES" "1" "2023-04-14" "1.0.0" "pyps idp show directories Manual"
.SH NAME
pyps\-idp\-show\-directories \- retrieve a list of directories from tenant
.SH SYNOPSIS
.B pyps idp show directories
[OPTIONS]
.SH DESCRIPTION
retrieve a list of directories from tenant
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
