.TH "PYPS K8S VDP KUBECONFIG" "1" "2023-01-01" "1.0.0" "pyps k8s vdp kubeconfig Manual"
.SH NAME
pyps\-k8s\-vdp\-kubeconfig \- create vdp kubeconfig for an organization
.SH SYNOPSIS
.B pyps k8s vdp kubeconfig
[OPTIONS] TARGET_ORG
.SH DESCRIPTION
create vdp kubeconfig for an organization
.SH OPTIONS
.TP
\fB\-P,\fP \-\-project TEXT
set project name
.TP
\fB\-n,\fP \-\-namespace TEXT
set default namespace
.TP
\fB\-m,\fP \-\-merge
merge the result with existing config
