.TH "PYPS VMC SDDC SHOW NSX CREDENTIALS" "1" "2023-04-14" "1.0.0" "pyps vmc sddc show nsx credentials Manual"
.SH NAME
pyps\-vmc\-sddc\-show\-nsx\-credentials \- show login credentials for NSX in a...
.SH SYNOPSIS
.B pyps vmc sddc show nsx credentials
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show login credentials for NSX in a specific SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
