.TH "PYPS VMC SDDC NSX SHOW ACTIVE-EDGE" "1" "2023-04-14" "1.0.0" "pyps vmc sddc nsx show active-edge Manual"
.SH NAME
pyps\-vmc\-sddc\-nsx\-show\-active-edge \- show active edge information for the SDDC
.SH SYNOPSIS
.B pyps vmc sddc nsx show active-edge
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show active edge information for the SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
.TP
\fB\-t,\fP \-\-ticket TEXT
CSSD or CSCM ticket asssociated with the RTS task  [default: CSSD-1234]
