.TH "PYPS VMC SDDC NSX" "1" "2023-04-14" "1.0.0" "pyps vmc sddc nsx Manual"
.SH NAME
pyps\-vmc\-sddc\-nsx \- manage NSX making up the SDDC
.SH SYNOPSIS
.B pyps vmc sddc nsx
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage NSX making up the SDDC
.SH COMMANDS
.PP
\fBedge-failover\fP
  perform edge failover actions for a...
  See \fBpyps vmc sddc nsx-edge-failover(1)\fP for full documentation on the \fBedge-failover\fP command.
.PP
\fBmaintenance\fP
  enter or exit transport maintenance mode...
  See \fBpyps vmc sddc nsx-maintenance(1)\fP for full documentation on the \fBmaintenance\fP command.
.PP
\fBssh-toggle\fP
  enable or disable SSH on NSX in a specific...
  See \fBpyps vmc sddc nsx-ssh-toggle(1)\fP for full documentation on the \fBssh-toggle\fP command.
.PP
\fBshow\fP
  show data about the NSX in a SDDC
  See \fBpyps vmc sddc nsx-show(1)\fP for full documentation on the \fBshow\fP command.
