.TH "PYPS VMC ONBOARD MENU" "1" "2023-04-14" "1.0.0" "pyps vmc onboard menu Manual"
.SH NAME
pyps\-vmc\-onboard\-menu \- launch a menu to perform customer...
.SH SYNOPSIS
.B pyps vmc onboard menu
[OPTIONS]
.SH DESCRIPTION
launch a menu to perform customer onboarding tasks in order of operation
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
.TP
\fB\-t,\fP \-\-ticket TEXT
provide CSSD ticket
.TP
\fB\-i,\fP \-\-internal
flag to create an internal organization vs. customer
