.TH "PYPS VMC ORG USER SHOW ROLES" "1" "2023-04-14" "1.0.0" "pyps vmc org user show roles Manual"
.SH NAME
pyps\-vmc\-org\-user\-show\-roles \- list roles associated with the user
.SH SYNOPSIS
.B pyps vmc org user show roles
[OPTIONS] [USER_NAME] [TARGET_ORG]
.SH DESCRIPTION
list roles associated with the user
