.TH "PYPS CSP AUTH SETUP" "1" "2023-04-14" "1.0.0" "pyps csp auth setup Manual"
.SH NAME
pyps\-csp\-auth\-setup \- setup your API access to a given CSP org
.SH SYNOPSIS
.B pyps csp auth setup
[OPTIONS]
.SH DESCRIPTION
setup your API access to a given CSP org
.SH OPTIONS
.TP
\fB\-i,\fP \-\-id TEXT
ID of the target CSP org
.TP
\fB\-n,\fP \-\-name TEXT
name of the target CSP org
