.TH "PYPS GIT SHOW REPOS" "1" "2023-03-07" "1.0.0" "pyps git show repos Manual"
.SH NAME
pyps\-git\-show\-repos \- show all repos registered in git
.SH SYNOPSIS
.B pyps git show repos
[OPTIONS]
.SH DESCRIPTION
show all repos registered in git
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
