.TH "PYPS VMC SHOW SDDC DRAAS VERSIONS" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc draas versions Manual"
.SH NAME
pyps\-vmc\-show\-sddc\-draas\-versions \- show details about draas versions
.SH SYNOPSIS
.B pyps vmc show sddc draas versions
[OPTIONS] [TARGET_ORG] [SDDC_ID]
.SH DESCRIPTION
show details about draas versions
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
