.TH "PYPS VMC SHOW SDDC DRAAS TASKS" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc draas tasks Manual"
.SH NAME
pyps\-vmc\-show\-sddc\-draas\-tasks \- show details about draas tasks
.SH SYNOPSIS
.B pyps vmc show sddc draas tasks
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
show details about draas tasks
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
