.TH "PYPS NEXUS SHOW MANIFESTS" "1" "2023-04-14" "1.0.0" "pyps nexus show manifests Manual"
.SH NAME
pyps\-nexus\-show\-manifests \- show all VMC manifests registered in nexus...
.SH SYNOPSIS
.B pyps nexus show manifests
[OPTIONS] [SERVICE]
.SH DESCRIPTION
show all VMC manifests registered in nexus repository for a particular service
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
