.TH "PYPS CONFIGS DELETE" "1" "2023-04-14" "1.0.0" "pyps configs delete Manual"
.SH NAME
pyps\-configs\-delete \- delete data saved in a configstore
.SH SYNOPSIS
.B pyps configs delete
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
delete data saved in a configstore
.SH COMMANDS
.PP
\fBprofile\fP
  delete an entire profile stored in a...
  See \fBpyps configs delete-profile(1)\fP for full documentation on the \fBprofile\fP command.
.PP
\fBproperty\fP
  delete a record stored in a configstore
  See \fBpyps configs delete-property(1)\fP for full documentation on the \fBproperty\fP command.
