.TH "PYPS VMC SDDC SHOW NSX STATUS" "1" "2023-03-19" "1.0.0" "pyps vmc sddc show nsx status Manual"
.SH NAME
pyps\-vmc\-sddc\-show\-nsx\-status \- show the status for NSX in a specific SDDC
.SH SYNOPSIS
.B pyps vmc sddc show nsx status
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show the status for NSX in a specific SDDC
.SH OPTIONS
.TP
\fB\-t,\fP \-\-ticket TEXT
CSSD or CSCM ticket asssociated with the RTS task  [default: CSSD-1234]
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
