.TH "PYPS VMC SDDC NSX SHOW VPN-STATES" "1" "2023-04-14" "1.0.0" "pyps vmc sddc nsx show vpn-states Manual"
.SH NAME
pyps\-vmc\-sddc\-nsx\-show\-vpn-states \- show the VPN session states for NSX in a...
.SH SYNOPSIS
.B pyps vmc sddc nsx show vpn-states
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show the VPN session states for NSX in a specific SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
