.TH "PYPS VMC SHOW SDDC" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc Manual"
.SH NAME
pyps\-vmc\-show\-sddc \- show info about VMC SDDC(s)
.SH SYNOPSIS
.B pyps vmc show sddc
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
show info about VMC SDDC(s)
.SH COMMANDS
.PP
\fBdetails\fP
  describe a specific SDDC
  See \fBpyps vmc show sddc-details(1)\fP for full documentation on the \fBdetails\fP command.
.PP
\fBall\fP
  show all SDDCs deployed in VMC on AWS
  See \fBpyps vmc show sddc-all(1)\fP for full documentation on the \fBall\fP command.
.PP
\fBpop\fP
  show info about POP
  See \fBpyps vmc show sddc-pop(1)\fP for full documentation on the \fBpop\fP command.
.PP
\fBesx\fP
  show data about the ESXi hosts in a SDDC
  See \fBpyps vmc show sddc-esx(1)\fP for full documentation on the \fBesx\fP command.
.PP
\fBnsx\fP
  show data about the NSX in a SDDC
  See \fBpyps vmc show sddc-nsx(1)\fP for full documentation on the \fBnsx\fP command.
.PP
\fBvcenter\fP
  show data about the vCenter server in a SDDC
  See \fBpyps vmc show sddc-vcenter(1)\fP for full documentation on the \fBvcenter\fP command.
.PP
\fBdraas\fP
  show info about VMC DRaaS
  See \fBpyps vmc show sddc-draas(1)\fP for full documentation on the \fBdraas\fP command.
