.TH "PYPS K8S CLUSTER PRESSURES" "1" "2023-01-01" "1.0.0" "pyps k8s cluster pressures Manual"
.SH NAME
pyps\-k8s\-cluster\-pressures \- show pressure across all clusters or on a...
.SH SYNOPSIS
.B pyps k8s cluster pressures
[OPTIONS] [CLUSTER_SHORT_NAME]
.SH DESCRIPTION
show pressure across all clusters or on a specific cluster
