.TH "PYPS GIT ACTION CLONE" "1" "2023-03-07" "1.0.0" "pyps git action clone Manual"
.SH NAME
pyps\-git\-action\-clone \- easily clone a repository using the HTTP...
.SH SYNOPSIS
.B pyps git action clone
[OPTIONS] [REPO_URL]
.SH DESCRIPTION
easily clone a repository using the HTTP repo url
.SH OPTIONS
.TP
\fB\-a,\fP \-\-all
clone all repositories from base group selected
