.TH "PYPS VMC SHOW IDP" "1" "2023-04-14" "1.0.0" "pyps vmc show idp Manual"
.SH NAME
pyps\-vmc\-show\-idp \- list all vIDM tenants with optional filter
.SH SYNOPSIS
.B pyps vmc show idp
[OPTIONS]
.SH DESCRIPTION
list all vIDM tenants with optional filter
.SH OPTIONS
.TP
\fB\-t,\fP \-\-tenants
show only tenant display names
.TP
\fB\-f,\fP \-\-filter TEXT
filter the result by key:value, key: or :value
