.TH "PYPS IDP USERS ADD" "1" "2023-04-14" "1.0.0" "pyps idp users add Manual"
.SH NAME
pyps\-idp\-users\-add \- add user to selected tenant
.SH SYNOPSIS
.B pyps idp users add
[OPTIONS]
.SH DESCRIPTION
add user to selected tenant
.SH OPTIONS
.TP
\fB\-u,\fP \-\-username TEXT
provide username to add  [required]
.TP
\fB\-f,\fP \-\-firstname TEXT
provide firstname  [required]
.TP
\fB\-l,\fP \-\-lastname TEXT
provide lastname  [required]
.TP
\fB\-e,\fP \-\-email TEXT
provide email address  [required]
.TP
\fB\-d,\fP \-\-domain TEXT
provide domain
