.TH "PYPS VMC ORG SHOW TASKS" "1" "2023-04-14" "1.0.0" "pyps vmc org show tasks Manual"
.SH NAME
pyps\-vmc\-org\-show\-tasks \- show tasks for a CSP org
.SH SYNOPSIS
.B pyps vmc org show tasks
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
show tasks for a CSP org
.SH OPTIONS
.TP
\fB\-s,\fP \-\-summary
display task summary
