.TH "PYPS JENKINS SHOW JOBS URLS" "1" "2023-04-14" "1.0.0" "pyps jenkins show jobs urls Manual"
.SH NAME
pyps\-jenkins\-show\-jobs\-urls \- show last 100 build urls for a specific...
.SH SYNOPSIS
.B pyps jenkins show jobs urls
[OPTIONS] [NAME]
.SH DESCRIPTION
show last 100 build urls for a specific job in jenkins
