.TH "PYPS FLY ACTION TRIGGER" "1" "2023-03-03" "1.0.0" "pyps fly action trigger Manual"
.SH NAME
pyps\-fly\-action\-trigger \- trigger a runway post-deploy job with it's...
.SH SYNOPSIS
.B pyps fly action trigger
[OPTIONS] TEAM
.SH DESCRIPTION
trigger a runway post-deploy job with it's service team name
