.TH "PYPS CSP ORG SHOW ACCESS-TOKEN" "1" "2023-04-14" "1.0.0" "pyps csp org show access-token Manual"
.SH NAME
pyps\-csp\-org\-show\-access-token \- API token for accessing the CSP functionality
.SH SYNOPSIS
.B pyps csp org show access-token
[OPTIONS]
.SH DESCRIPTION
API token for accessing the CSP functionality
