.TH "PYPS JC STOP" "1" "2023-04-14" "1.0.0" "pyps jc stop Manual"
.SH NAME
pyps\-jc\-stop \- transition tickets to close, with...
.SH SYNOPSIS
.B pyps jc stop
[OPTIONS] [CHANNEL]...
.SH DESCRIPTION
transition tickets to close, with necessary pipeline tasks included
.SH OPTIONS
.TP
\fB\-k,\fP \-\-key TEXT
JIRA ticket number (key) to post a comment on; i.e. PUBSECSRE-123
.TP
\fB\-p,\fP \-\-project TEXT
JIRA project to search for tickets to transition; i.e. PUBSECSRE
.TP
\fB\-e,\fP \-\-emoji TEXT
emoji name to react with
