.TH "PYPS NEXUS SHOW USER" "1" "2023-04-14" "1.0.0" "pyps nexus show user Manual"
.SH NAME
pyps\-nexus\-show\-user \- show user information registered in nexus...
.SH SYNOPSIS
.B pyps nexus show user
[OPTIONS] [NAME]
.SH DESCRIPTION
show user information registered in nexus for a specific user
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
