.TH "PYPS VMC SHOW SDDC NSX STANDBY-EDGE" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc nsx standby-edge Manual"
.SH NAME
pyps\-vmc\-show\-sddc\-nsx\-standby-edge \- show standby edge information for the SDDC
.SH SYNOPSIS
.B pyps vmc show sddc nsx standby-edge
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show standby edge information for the SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
.TP
\fB\-t,\fP \-\-ticket TEXT
CSSD or CSCM ticket asssociated with the RTS task  [default: CSSD-1234]
