.TH "PYPS VMC ORG SHOW SDDCS" "1" "2023-04-14" "1.0.0" "pyps vmc org show sddcs Manual"
.SH NAME
pyps\-vmc\-org\-show\-sddcs \- show all sddcs deployed under a given org
.SH SYNOPSIS
.B pyps vmc org show sddcs
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
show all sddcs deployed under a given org
.SH OPTIONS
.TP
\fB\-o,\fP \-\-only\-aws\-ready
only show SDDCs in AWS and in READY state
.TP
\fB\-v,\fP \-\-version
only show versions of the SDDCs
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
