.TH "PYPS IDP TENANTS DELETE" "1" "2023-04-14" "1.0.0" "pyps idp tenants delete Manual"
.SH NAME
pyps\-idp\-tenants\-delete \- delete child tenant
.SH SYNOPSIS
.B pyps idp tenants delete
[OPTIONS]
.SH DESCRIPTION
delete child tenant
.SH OPTIONS
.TP
\fB\-n,\fP \-\-name TEXT
provide tenant name deletion
