.TH "PYPS JFROG" "1" "2023-03-03" "1.0.0" "pyps jfrog Manual"
.SH NAME
pyps\-jfrog \- VMware JFROG CLI Client -> Current...
.SH SYNOPSIS
.B pyps jfrog
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
VMware JFROG CLI Client -> Current Profile: [0;32m[4mDEFAULT[0m
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-p,\fP \-\-profile TEXT
user profile for JFROG operations
.SH COMMANDS
.PP
\fBauth\fP
  perform authentication operations against...
  See \fBpyps jfrog-auth(1)\fP for full documentation on the \fBauth\fP command.
.PP
\fBshow\fP
  retrieve information from jfrog artifacts
  See \fBpyps jfrog-show(1)\fP for full documentation on the \fBshow\fP command.
.PP
\fBaction\fP
  action tasks for jfrog artifactory
  See \fBpyps jfrog-action(1)\fP for full documentation on the \fBaction\fP command.
