.TH "PYPS CSP ORG SHOW ORG-ID" "1" "2023-04-14" "1.0.0" "pyps csp org show org-id Manual"
.SH NAME
pyps\-csp\-org\-show\-org-id \- lookup a CSP org ID using the name...
.SH SYNOPSIS
.B pyps csp org show org-id
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
lookup a CSP org ID using the name configured for it in csptools
