.TH "PYPS VMC SDDC" "1" "2023-04-14" "1.0.0" "pyps vmc sddc Manual"
.SH NAME
pyps\-vmc\-sddc \- manage and view info about SDDCs
.SH SYNOPSIS
.B pyps vmc sddc
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage and view info about SDDCs
.SH COMMANDS
.PP
\fBcreate\fP
  deploy a new SDDC in VMC
  See \fBpyps vmc sddc-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBdelete\fP
  delete a specific SDDC in a given org
  See \fBpyps vmc sddc-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBnotify\fP
  trigger a console notification for the...
  See \fBpyps vmc sddc-notify(1)\fP for full documentation on the \fBnotify\fP command.
.PP
\fBshow\fP
  show info about VMC SDDC(s)
  See \fBpyps vmc sddc-show(1)\fP for full documentation on the \fBshow\fP command.
.PP
\fBpop\fP
  connect to, manage and view info about...
  See \fBpyps vmc sddc-pop(1)\fP for full documentation on the \fBpop\fP command.
.PP
\fBesx\fP
  manage ESXi hosts making up the SDDC
  See \fBpyps vmc sddc-esx(1)\fP for full documentation on the \fBesx\fP command.
.PP
\fBnsx\fP
  manage NSX making up the SDDC
  See \fBpyps vmc sddc-nsx(1)\fP for full documentation on the \fBnsx\fP command.
.PP
\fBvcenter\fP
  manage vCenter servers in a SDDC
  See \fBpyps vmc sddc-vcenter(1)\fP for full documentation on the \fBvcenter\fP command.
.PP
\fBdraas\fP
  manage and view info about draas
  See \fBpyps vmc sddc-draas(1)\fP for full documentation on the \fBdraas\fP command.
.PP
\fBbackup\fP
  manage SDDC backups
  See \fBpyps vmc sddc-backup(1)\fP for full documentation on the \fBbackup\fP command.
.PP
\fBrestore\fP
  restore vCenter or NSX-T from backup
  See \fBpyps vmc sddc-restore(1)\fP for full documentation on the \fBrestore\fP command.
