.TH "PYPS GIT SHOW PROJECTS" "1" "2023-03-07" "1.0.0" "pyps git show projects Manual"
.SH NAME
pyps\-git\-show\-projects \- list all projects in Gitlab that you have...
.SH SYNOPSIS
.B pyps git show projects
[OPTIONS]
.SH DESCRIPTION
list all projects in Gitlab that you have access to
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
.TP
\fB\-p,\fP \-\-pattern TEXT
.PP
