.TH "PYPS JIRA PROJECT" "1" "2023-04-14" "1.0.0" "pyps jira project Manual"
.SH NAME
pyps\-jira\-project \- manage JIRA projects
.SH SYNOPSIS
.B pyps jira project
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage JIRA projects
.SH COMMANDS
.PP
\fBsearch\fP
  show a summary of projects matching the...
  See \fBpyps jira project-search(1)\fP for full documentation on the \fBsearch\fP command.
