.TH "PYPS VMC SDDC DRAAS SHOW VERSIONS" "1" "2023-04-14" "1.0.0" "pyps vmc sddc draas show versions Manual"
.SH NAME
pyps\-vmc\-sddc\-draas\-show\-versions \- show details about draas versions
.SH SYNOPSIS
.B pyps vmc sddc draas show versions
[OPTIONS] [TARGET_ORG] [SDDC_ID]
.SH DESCRIPTION
show details about draas versions
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
