.TH "PYPS VMC USER SESSION" "1" "2023-04-14" "1.0.0" "pyps vmc user session Manual"
.SH NAME
pyps\-vmc\-user\-session \- manage user session settings
.SH SYNOPSIS
.B pyps vmc user session
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage user session settings
.SH COMMANDS
.PP
\fBdelete\fP
  delete active user session
  See \fBpyps vmc user session-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBlimit\fP
  change a user's active session limit
  See \fBpyps vmc user session-limit(1)\fP for full documentation on the \fBlimit\fP command.
