.TH "PYPS VMC SDDC SHOW VCENTER CREDENTIALS" "1" "2023-04-14" "1.0.0" "pyps vmc sddc show vcenter credentials Manual"
.SH NAME
pyps\-vmc\-sddc\-show\-vcenter\-credentials \- show login credentials for the vCenter...
.SH SYNOPSIS
.B pyps vmc sddc show vcenter credentials
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show login credentials for the vCenter server in a specific SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
