.TH "PYPS VMC SHOW SDDC ALL" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc all Manual"
.SH NAME
pyps\-vmc\-show\-sddc\-all \- show all SDDCs deployed in VMC on AWS
.SH SYNOPSIS
.B pyps vmc show sddc all
[OPTIONS]
.SH DESCRIPTION
show all SDDCs deployed in VMC on AWS
.SH OPTIONS
.TP
\fB\-a,\fP \-\-auth TEXT
org id/name to use for authentication
.TP
\fB\-o,\fP \-\-only\-aws\-ready
only show SDDCs in AWS and in READY state
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
