.TH "PYPS CONFLUENCE SHOW CONFIG" "1" "2023-03-03" "1.0.0" "pyps confluence show config Manual"
.SH NAME
pyps\-confluence\-show\-config \- retrieve the entire content of...
.SH SYNOPSIS
.B pyps confluence show config
[OPTIONS]
.SH DESCRIPTION
retrieve the entire content of confluence's configstore instance
