.TH "PYPS NEXUS" "1" "2023-04-14" "1.0.0" "pyps nexus Manual"
.SH NAME
pyps\-nexus \- VMware NXS CLI Client[40GCurrent Profile:...
.SH SYNOPSIS
.B pyps nexus
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
VMware NXS CLI Client[40GCurrent Profile: [0;32m[4mDEFAULT[0m
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-p,\fP \-\-profile TEXT
user profile for Nexus operations
.SH COMMANDS
.PP
\fBauth\fP
  perform authentication operations against...
  See \fBpyps nexus-auth(1)\fP for full documentation on the \fBauth\fP command.
.PP
\fBshow\fP
  retrieve information from Nexus
  See \fBpyps nexus-show(1)\fP for full documentation on the \fBshow\fP command.
