.TH "PYPS IDP SHOW TENANT-CONFIG" "1" "2023-04-14" "1.0.0" "pyps idp show tenant-config Manual"
.SH NAME
pyps\-idp\-show\-tenant-config \- retrieve the entire tenant config
.SH SYNOPSIS
.B pyps idp show tenant-config
[OPTIONS]
.SH DESCRIPTION
retrieve the entire tenant config
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
