.TH "PYPS K8S NODES RUN" "1" "2023-01-01" "1.0.0" "pyps k8s nodes run Manual"
.SH NAME
pyps\-k8s\-nodes\-run \- run a command on all nodes in a specific...
.SH SYNOPSIS
.B pyps k8s nodes run
[OPTIONS] CMD [CLUSTER_SHORT_NAME]
.SH DESCRIPTION
run a command on all nodes in a specific cluster
.SH OPTIONS
.TP
\fB\-m,\fP \-\-masters
run only against master nodes
.TP
\fB\-v,\fP \-\-var_only
display only vars
