.TH "PYPS SECRETS DOWNLOAD" "1" "2023-04-14" "1.0.0" "pyps secrets download Manual"
.SH NAME
pyps\-secrets\-download \- download secrets from s3 to local storage
.SH SYNOPSIS
.B pyps secrets download
[OPTIONS] [SOURCE]
.SH DESCRIPTION
download secrets from s3 to local storage
.SH OPTIONS
.TP
\fB\-\-destination\fP TEXT
provide a local destination for download  [default: /share/home/stacksc]
