.TH "PYPS VMC SHOW ORG ALL" "1" "2023-04-14" "1.0.0" "pyps vmc show org all Manual"
.SH NAME
pyps\-vmc\-show\-org\-all \- show all CSP orgs registered in VMC
.SH SYNOPSIS
.B pyps vmc show org all
[OPTIONS]
.SH DESCRIPTION
show all CSP orgs registered in VMC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
