.TH "PYPS VMC ACCOUNT SHOW" "1" "2023-04-14" "1.0.0" "pyps vmc account show Manual"
.SH NAME
pyps\-vmc\-account\-show \- show info about AWS account(s)
.SH SYNOPSIS
.B pyps vmc account show
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
show info about AWS account(s)
.SH COMMANDS
.PP
\fBall\fP
  show all AWS accounts added to VMC
  See \fBpyps vmc account show-all(1)\fP for full documentation on the \fBall\fP command.
