.TH "PYPS JIRA ISSUE EXTRACT" "1" "2023-04-14" "1.0.0" "pyps jira issue extract Manual"
.SH NAME
pyps\-jira\-issue\-extract \- look for specific data in the description...
.SH SYNOPSIS
.B pyps jira issue extract
[OPTIONS] ISSUE_KEYS...
.SH DESCRIPTION
look for specific data in the description of a given issue
.SH OPTIONS
.TP
\fB\-k,\fP \-\-key TEXT
data key to lookup  [required]
.TP
\fB\-e,\fP \-\-exact
only grab exact matches
