.TH "PYPS CONFIGS SHOW" "1" "2023-04-14" "1.0.0" "pyps configs show Manual"
.SH NAME
pyps\-configs\-show \- show records stored in a configstore; you...
.SH SYNOPSIS
.B pyps configs show
[OPTIONS] CONFIGSTORE_NAME...
.SH DESCRIPTION
show records stored in a configstore; you can use profile and record names to narrow down the results
