.TH "PYPS VMC SDDC NOTIFY" "1" "2023-04-14" "1.0.0" "pyps vmc sddc notify Manual"
.SH NAME
pyps\-vmc\-sddc\-notify \- trigger a console notification for the...
.SH SYNOPSIS
.B pyps vmc sddc notify
[OPTIONS] [TARGET_ORG] [SDDC_ID]
.SH DESCRIPTION
trigger a console notification for the Target Org and SDDC
