.TH "PYPS SECRETS SET-POLICY" "1" "2023-04-14" "1.0.0" "pyps secrets set-policy Manual"
.SH NAME
pyps\-secrets\-set-policy \- enable or disable VPC access to secrets...
.SH SYNOPSIS
.B pyps secrets set-policy
[OPTIONS] [[off|on]]
.SH DESCRIPTION
enable or disable VPC access to secrets using policies
