.TH "PYPS CSP USER" "1" "2023-04-14" "1.0.0" "pyps csp user Manual"
.SH NAME
pyps\-csp\-user \- manage users in CSP orgs for VMC
.SH SYNOPSIS
.B pyps csp user
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage users in CSP orgs for VMC
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-m,\fP \-\-menu
launch a menu driven interface for CSP user add/remove actions
.SH COMMANDS
.PP
\fBadd\fP
  add user to a CSP org
  See \fBpyps csp user-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBremove\fP
  remove an user from a CSP org
  See \fBpyps csp user-remove(1)\fP for full documentation on the \fBremove\fP command.
.PP
\fBsearch\fP
  search for a user in CSP
  See \fBpyps csp user-search(1)\fP for full documentation on the \fBsearch\fP command.
.PP
\fBsession\fP
  manage user session settings
  See \fBpyps csp user-session(1)\fP for full documentation on the \fBsession\fP command.
.PP
\fBrole\fP
  manage user roles within an organization
  See \fBpyps csp user-role(1)\fP for full documentation on the \fBrole\fP command.
.PP
\fBshow\fP
  display info about CSP user(s)
  See \fBpyps csp user-show(1)\fP for full documentation on the \fBshow\fP command.
