.TH "PYPS FLY SHOW POST-DEPLOY" "1" "2023-03-03" "1.0.0" "pyps fly show post-deploy Manual"
.SH NAME
pyps\-fly\-show\-post-deploy \- get post-deploy results per selected team...
.SH SYNOPSIS
.B pyps fly show post-deploy
[OPTIONS] [TEAM]
.SH DESCRIPTION
get post-deploy results per selected team in Concourse
.SH OPTIONS
.TP
\fB\-p,\fP \-\-pattern TEXT
pattern to search on due to the number of pipelines
.TP
\fB\-l,\fP \-\-last
get the last build only from the post-deploy job
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
