.TH "PYPS VMC SDDC SHOW POP" "1" "2023-04-14" "1.0.0" "pyps vmc sddc show pop Manual"
.SH NAME
pyps\-vmc\-sddc\-show\-pop \- show info about POP
.SH SYNOPSIS
.B pyps vmc sddc show pop
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
show info about POP
.SH COMMANDS
.PP
\fBdetails\fP
  show details about a POP instance for a...
  See \fBpyps vmc sddc show pop-details(1)\fP for full documentation on the \fBdetails\fP command.
