.TH "PYPS VMC SDDC POP SHOW DETAILS" "1" "2023-04-14" "1.0.0" "pyps vmc sddc pop show details Manual"
.SH NAME
pyps\-vmc\-sddc\-pop\-show\-details \- show details about a POP instance for a...
.SH SYNOPSIS
.B pyps vmc sddc pop show details
[OPTIONS] [TARGET_ORG] [SDDC_ID]
.SH DESCRIPTION
show details about a POP instance for a given SDDC in a specific org
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
