.TH "PYPS GIT SHOW" "1" "2023-03-07" "1.0.0" "pyps git show Manual"
.SH NAME
pyps\-git\-show \- retrieve information from Git
.SH SYNOPSIS
.B pyps git show
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
retrieve information from Git
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-m,\fP \-\-menu
launch a menu driven interface for common Git user actions
.SH COMMANDS
.PP
\fBconfig\fP
  retrieve the entire content of gitools'...
  See \fBpyps git show-config(1)\fP for full documentation on the \fBconfig\fP command.
.PP
\fBrepos\fP
  show all repos registered in git
  See \fBpyps git show-repos(1)\fP for full documentation on the \fBrepos\fP command.
.PP
\fBuser\fP
  show user information registered in git...
  See \fBpyps git show-user(1)\fP for full documentation on the \fBuser\fP command.
.PP
\fBprojects\fP
  list all projects in Gitlab that you have...
  See \fBpyps git show-projects(1)\fP for full documentation on the \fBprojects\fP command.
.PP
\fBgroups\fP
  list all groups in Gitlab that you have...
  See \fBpyps git show-groups(1)\fP for full documentation on the \fBgroups\fP command.
.PP
\fBgroup\fP
  list a specific group in Gitlab that you...
  See \fBpyps git show-group(1)\fP for full documentation on the \fBgroup\fP command.
.PP
\fBnamespaces\fP
  list all namespaces in Gitlab that you...
  See \fBpyps git show-namespaces(1)\fP for full documentation on the \fBnamespaces\fP command.
.PP
\fBaccess-token\fP
  API token for accessing the GIT functionality
  See \fBpyps git show-access-token(1)\fP for full documentation on the \fBaccess-token\fP command.
.PP
\fBaccess-token-age\fP
  how long the current access token will...
  See \fBpyps git show-access-token-age(1)\fP for full documentation on the \fBaccess-token-age\fP command.
