.TH "PYPS GIT" "1" "2023-03-07" "1.0.0" "pyps git Manual"
.SH NAME
pyps\-git \- VMware GIT CLI Client -> Current Profile:...
.SH SYNOPSIS
.B pyps git
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
VMware GIT CLI Client -> Current Profile: [0;32m[4mDEFAULT[0m
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-p,\fP \-\-profile TEXT
user profile for git operations
.SH COMMANDS
.PP
\fBaction\fP
  action tasks for Gitlab
  See \fBpyps git-action(1)\fP for full documentation on the \fBaction\fP command.
.PP
\fBauth\fP
  perform authentication operations against git
  See \fBpyps git-auth(1)\fP for full documentation on the \fBauth\fP command.
.PP
\fBshow\fP
  retrieve information from Git
  See \fBpyps git-show(1)\fP for full documentation on the \fBshow\fP command.
