.TH "PYPS CSP OAUTH SHOW APPS" "1" "2023-04-14" "1.0.0" "pyps csp oauth show apps Manual"
.SH NAME
pyps\-csp\-oauth\-show\-apps \- display list of oauth apps for selected org
.SH SYNOPSIS
.B pyps csp oauth show apps
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
display list of oauth apps for selected org
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
.TP
\fB\-m,\fP \-\-managed
display only managed oauth-apps for target org
