.TH "PYPS VMC ORG SHOW ACCESS-TOKEN-AGE" "1" "2023-04-14" "1.0.0" "pyps vmc org show access-token-age Manual"
.SH NAME
pyps\-vmc\-org\-show\-access-token-age \- how long the current access token will...
.SH SYNOPSIS
.B pyps vmc org show access-token-age
[OPTIONS]
.SH DESCRIPTION
how long the current access token will remain active
