.TH "PYPS VMC SHOW USER SERVICE-ROLES" "1" "2023-04-14" "1.0.0" "pyps vmc show user service-roles Manual"
.SH NAME
pyps\-vmc\-show\-user\-service-roles \- list service roles associated with the user
.SH SYNOPSIS
.B pyps vmc show user service-roles
[OPTIONS] [USER_NAME] [TARGET_ORG]
.SH DESCRIPTION
list service roles associated with the user
