.TH "PYPS VMC SDDC BACKUP SHOW" "1" "2023-04-14" "1.0.0" "pyps vmc sddc backup show Manual"
.SH NAME
pyps\-vmc\-sddc\-backup\-show \- show all backups for a specific SDDC
.SH SYNOPSIS
.B pyps vmc sddc backup show
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
show all backups for a specific SDDC
.SH OPTIONS
.TP
\fB\-n,\fP \-\-name\-only
only show backup names
