.TH "PYPS VMC SHOW SDDC NSX SUMMARY" "1" "2023-04-14" "1.0.0" "pyps vmc show sddc nsx summary Manual"
.SH NAME
pyps\-vmc\-show\-sddc\-nsx\-summary \- quick summary of NSX related information...
.SH SYNOPSIS
.B pyps vmc show sddc nsx summary
[OPTIONS] [SDDC_ID]
.SH DESCRIPTION
quick summary of NSX related information under a given SDDC
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
