.TH "PYPS VMC ACCOUNT" "1" "2023-04-14" "1.0.0" "pyps vmc account Manual"
.SH NAME
pyps\-vmc\-account \- manage AWS accounts used in VMC
.SH SYNOPSIS
.B pyps vmc account
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage AWS accounts used in VMC
.SH COMMANDS
.PP
\fBimport\fP
  import AWS account into VMC
  See \fBpyps vmc account-import(1)\fP for full documentation on the \fBimport\fP command.
.PP
\fBassociate\fP
  associate an AWS account with a VMC org
  See \fBpyps vmc account-associate(1)\fP for full documentation on the \fBassociate\fP command.
.PP
\fBdisassociate\fP
  disassociate an AWS account with a VMC org
  See \fBpyps vmc account-disassociate(1)\fP for full documentation on the \fBdisassociate\fP command.
.PP
\fBdelete\fP
  delete an AWS account from VMC
  See \fBpyps vmc account-delete(1)\fP for full documentation on the \fBdelete\fP command.
.PP
\fBshow\fP
  show info about AWS account(s)
  See \fBpyps vmc account-show(1)\fP for full documentation on the \fBshow\fP command.
