.TH "PYPS CSP USER SHOW ORGS" "1" "2023-04-14" "1.0.0" "pyps csp user show orgs Manual"
.SH NAME
pyps\-csp\-user\-show\-orgs \- list orgs associated with the user
.SH SYNOPSIS
.B pyps csp user show orgs
[OPTIONS] [USER_NAME] [TARGET_ORG]
.SH DESCRIPTION
list orgs associated with the user
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
