.TH "PYPS CSP USER SHOW SESSIONS" "1" "2023-04-14" "1.0.0" "pyps csp user show sessions Manual"
.SH NAME
pyps\-csp\-user\-show\-sessions \- get max session limit for the user and...
.SH SYNOPSIS
.B pyps csp user show sessions
[OPTIONS] [USER_ID] [TARGET_ORG]
.SH DESCRIPTION
get max session limit for the user and their active sessions
