.TH "PYPS IDP USERS" "1" "2023-04-14" "1.0.0" "pyps idp users Manual"
.SH NAME
pyps\-idp\-users \- manage users per tenant
.SH SYNOPSIS
.B pyps idp users
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
manage users per tenant
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-m,\fP \-\-menu
launch a menu driven interface for common CSP user actions
.SH COMMANDS
.PP
\fBremove\fP
  remove user from selected tenant
  See \fBpyps idp users-remove(1)\fP for full documentation on the \fBremove\fP command.
.PP
\fBadd\fP
  add user to selected tenant
  See \fBpyps idp users-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBpassword-reset\fP
  password-reset per selected user and target
  See \fBpyps idp users-password-reset(1)\fP for full documentation on the \fBpassword-reset\fP command.
