.TH "PYPS JENKINS SHOW JOBS INFO" "1" "2023-04-14" "1.0.0" "pyps jenkins show jobs info Manual"
.SH NAME
pyps\-jenkins\-show\-jobs\-info \- show details for a specific build and job...
.SH SYNOPSIS
.B pyps jenkins show jobs info
[OPTIONS] [NAME]
.SH DESCRIPTION
show details for a specific build and job name in jenkins
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
