.TH "PYPS JFROG SHOW" "1" "2023-03-03" "1.0.0" "pyps jfrog show Manual"
.SH NAME
pyps\-jfrog\-show \- retrieve information from jfrog artifacts
.SH SYNOPSIS
.B pyps jfrog show
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
retrieve information from jfrog artifacts
.SH OPTIONS
.TP
\fB\-d,\fP \-\-debug [0|1|2]
0 = no output, 1 = default, 2 = debug on
.TP
\fB\-m,\fP \-\-menu
launch a menu driven interface for common CSP user actions
.SH COMMANDS
.PP
\fBconfig\fP
  retrieve the entire content of artifact's...
  See \fBpyps jfrog show-config(1)\fP for full documentation on the \fBconfig\fP command.
.PP
\fBaccess-token\fP
  API token for accessing the jfrog...
  See \fBpyps jfrog show-access-token(1)\fP for full documentation on the \fBaccess-token\fP command.
.PP
\fBaccess-token-age\fP
  how long the current access token will...
  See \fBpyps jfrog show-access-token-age(1)\fP for full documentation on the \fBaccess-token-age\fP command.
.PP
\fBrepos\fP
  display repositories found in JFROG
  See \fBpyps jfrog show-repos(1)\fP for full documentation on the \fBrepos\fP command.
.PP
\fBrepo\fP
  display packages per repository selected...
  See \fBpyps jfrog show-repo(1)\fP for full documentation on the \fBrepo\fP command.
