.TH "PYPS VMC SHOW USER ORGS" "1" "2023-04-14" "1.0.0" "pyps vmc show user orgs Manual"
.SH NAME
pyps\-vmc\-show\-user\-orgs \- list orgs associated with the user
.SH SYNOPSIS
.B pyps vmc show user orgs
[OPTIONS] [USER_NAME] [TARGET_ORG]
.SH DESCRIPTION
list orgs associated with the user
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
