.TH "PYPS CSP ORG USER SHOW" "1" "2023-04-14" "1.0.0" "pyps csp org user show Manual"
.SH NAME
pyps\-csp\-org\-user\-show \- display info about CSP user(s)
.SH SYNOPSIS
.B pyps csp org user show
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
display info about CSP user(s)
.SH COMMANDS
.PP
\fBorgs\fP
  list orgs associated with the user
  See \fBpyps csp org user show-orgs(1)\fP for full documentation on the \fBorgs\fP command.
.PP
\fBdetails\fP
  list details about the user
  See \fBpyps csp org user show-details(1)\fP for full documentation on the \fBdetails\fP command.
.PP
\fBroles\fP
  list roles associated with the user
  See \fBpyps csp org user show-roles(1)\fP for full documentation on the \fBroles\fP command.
.PP
\fBservice-roles\fP
  list service roles associated with the user
  See \fBpyps csp org user show-service-roles(1)\fP for full documentation on the \fBservice-roles\fP command.
.PP
\fBuserid\fP
  get userid for a specific user in CSP
  See \fBpyps csp org user show-userid(1)\fP for full documentation on the \fBuserid\fP command.
.PP
\fBsessions\fP
  get max session limit for the user and...
  See \fBpyps csp org user show-sessions(1)\fP for full documentation on the \fBsessions\fP command.
