.TH "PYPS VMC SHOW ORG FEATURES" "1" "2023-04-14" "1.0.0" "pyps vmc show org features Manual"
.SH NAME
pyps\-vmc\-show\-org\-features \- list enabled features for a CSP org
.SH SYNOPSIS
.B pyps vmc show org features
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
list enabled features for a CSP org
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
