.TH "PYPS AWS SECRETS SET-POLICY" "1" "2023-03-10" "1.0.0" "pyps aws secrets set-policy Manual"
.SH NAME
pyps\-aws\-secrets\-set-policy \- enable or disable VPC access to secrets...
.SH SYNOPSIS
.B pyps aws secrets set-policy
[OPTIONS] [[off|on]]
.SH DESCRIPTION
enable or disable VPC access to secrets using policies
