.TH "PYPS CSP ORG SHOW ACCOUNT" "1" "2023-04-14" "1.0.0" "pyps csp org show account Manual"
.SH NAME
pyps\-csp\-org\-show\-account \- show details about AWS account associated...
.SH SYNOPSIS
.B pyps csp org show account
[OPTIONS] [TARGET_ORG]
.SH DESCRIPTION
show details about AWS account associated with a given org
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; don't reduce output
