.TH "PYPS VMC RTS" "1" "2023-04-14" "1.0.0" "pyps vmc rts Manual"
.SH NAME
pyps\-vmc\-rts \- run and manage RTS tasks
.SH SYNOPSIS
.B pyps vmc rts
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
run and manage RTS tasks
.SH COMMANDS
.PP
\fBrun\fP
  run ad-hoc RTS script
  See \fBpyps vmc rts-run(1)\fP for full documentation on the \fBrun\fP command.
.PP
\fBstatus\fP
  check status of a given RTS task
  See \fBpyps vmc rts-status(1)\fP for full documentation on the \fBstatus\fP command.
.PP
\fBdetails\fP
  get details about a specific RTS task
  See \fBpyps vmc rts-details(1)\fP for full documentation on the \fBdetails\fP command.
