.TH "PYPS NEXUS SHOW REPOS" "1" "2023-04-14" "1.0.0" "pyps nexus show repos Manual"
.SH NAME
pyps\-nexus\-show\-repos \- show all repos registered in nexus
.SH SYNOPSIS
.B pyps nexus show repos
[OPTIONS]
.SH DESCRIPTION
show all repos registered in nexus
.SH OPTIONS
.TP
\fB\-r,\fP \-\-raw
display raw json; dont reduce output
