.TH "PYPS VMC IDP USERS" "1" "2023-04-14" "1.0.0" "pyps vmc idp users Manual"
.SH NAME
pyps\-vmc\-idp\-users \- list all vIDM users belonging to a tenant
.SH SYNOPSIS
.B pyps vmc idp users
[OPTIONS]
.SH DESCRIPTION
list all vIDM users belonging to a tenant
.SH OPTIONS
.TP
\fB\-t,\fP \-\-tenant TEXT
display users belonging to a specific tenant
