.TH "PYPS VMC SHOW ORG ACCESS-TOKEN-AGE" "1" "2023-04-14" "1.0.0" "pyps vmc show org access-token-age Manual"
.SH NAME
pyps\-vmc\-show\-org\-access-token-age \- how long the current access token will...
.SH SYNOPSIS
.B pyps vmc show org access-token-age
[OPTIONS]
.SH DESCRIPTION
how long the current access token will remain active
