.TH "PYPS VMC ORG PROPERTY SET" "1" "2023-04-14" "1.0.0" "pyps vmc org property set Manual"
.SH NAME
pyps\-vmc\-org\-property\-set \- add a property to an org config
.SH SYNOPSIS
.B pyps vmc org property set
[OPTIONS] [TARGET_ORG] PROPERTY_NAME PROPERTY_VALUE
.SH DESCRIPTION
add a property to an org config
